// In "menu_str", all words come from the left menu 
var menu_str = 
{
	status:"Trạng thái",
	status6:"Trạng thái IPv6",
	qs:"Quick Setup",
	sysmod:"Chế độ hoạt động",
	network:"Mạng ",
	wan:"WAN",
	wan6:"IPv6 WAN",
	ewan:"EWAN",
	usb3g:"Cài đặt 3G  ",
	group:"Giao diện nhóm",
	lan:"LAN",
	lan6:"LAN IPv6",
	macclone:"Sao MAC",
	alg:"Cài đặt ALG",
	dsl:"Thiết lập DSL",
	autopvc:"PVC Tự động phát hiện",
	ipsec:"IPSec VPN",
	iptv:"IPTV",
	dhcp:"DHCP",
	dhcpserver:"Thiết lập DHCP",
	dhcpclient:"Danh sách khách hàng DHCP",
	addrresrv:"Địa chỉ dự trữ",
	condpool:"Vùng lưu trữ có điều kiện",
	dualband:"Lựa chọn băng tần kép",
	wl:"Mạng không dây ",
	wl2g:"Mạng không dây 2.4GHz",
	wlbasic:"Cài đặt cơ bản",
	wlqss:"WPS",
	wlsec:"Bảo mật mạng không dây",
	wlsche:"Thời gian biểu mạng không dây",
	wlacl:"Bộ lọc MAC mạng không dây",
	wladv:"Nâng cao mạng không dây",
	wlstat:"Thống kê mạng không dây",
	wl5g:"Mạng không dây 5GHz",
	wlbasic5g:"Cài đặt cơ bản",
	wlqss5g:"WPS",
	wlsec5g:"Bảo mật mạng không dây",
	wlsche5g:"Thời gian biểu mạng không dây",
	wlacl5g:"Bộ lọc MAC mạng không dây",
	wladv5g:"Nâng cao mạng không dây",
	wlstat5g:"Thống kê mạng không dây",
	wlguest:"Mạng khách",
    wlguestBasic:"Cài đặt cơ bản",
	wlguestBasic2G:"Cài đặt cơ bản mạng 2.4GHz",
	wlguestStats:"Trạng thái mạng khách",
	wlguestStats2G:"Trạng thái mạng khách 2.4GHz",
	wlguestBasic5g:"Cài đặt cơ bản mạng 5GHz",
	wlguestStats5g:"Trạng thái mạng khách 5GHz",
	voip:"Thoại  ",
	sipac:"Tài khoản SIP",
	dialplan:"Dial Plan",
	planlist:"Danh sách Dial Plan",
	fbdcall:"Chặn cuộc gọi",
	emgcall:"Cuộc gọi khẩn cấp",
	sip:"Cài đặt điện thoại",
	sipadv:"Cài đặt nâng cao ",
	spddial:"Quay số tốc độ",
	calllog:"Nhật ký cuộc gọi",
	callfw:"Tường lửa cuộc gọi",
	callfwmod:"Cài đặt chế độ",
	callfwbl:"Danh sách đen",
	callfwwl:"Danh sách trắng",
	usbmail:"Hộp thư thoại USB  ",
	usb:"Cài đặt USB",
	usbmanage:"Lưu trữ USB Mass ",
	usbac:"Tài khoản người dùng",
	featurecode:"Cài đặt tính năng mật mã",
	samba:"Chia sẻ lưu trữ",
	ftp:"Máy chủ FTP ",
	dlna:"Máy chủ đa phương tiện",
	printer:"Máy chủ in",
	hw_nat:"NAT",
	router:"Routing nâng cao",
	gw:"Cổng mặc định",
	rt:"Danh sách tuyến tĩnh",
	routetbl:"Bảng định tuyến hệ thống",
	rip:"Cài đặt RIP",
	router6:"Cài đặt định tuyến IPv6",
	gw6:"Gateway mặc định IPv6",
	rt6:"Định tuyến tĩnh IPv6",
	fwd:"Đang chuyển tiếp",
	vs:"Máy chủ ảo  ",
	pt:"Cổng đang kích hoạt  ",
	dmz:"DMZ",
	upnp:"UPnP",
	security:"Bảo mật",
	basicSec:"Bảo mật cơ bản",
	pc:"Quyền kiểm soát của phụ huynh  ",
	fw:"Kiểm soát truy cập",
	fwrule:"Quy tắc  ",
	fwlan:"Host",
	fwwan:"Mục tiêu",
	fwsch:"Thời gian biểu",
	ddos:"Bảo mật nâng cao",
	fw6:"Tường lửa IPv6",
	fw6rule:"Quy tắc IPv6 ",
	fw6lan:"Máy chủ LAN IPv6",
	fw6wan:"Máy chủ WAN IPv6",
	fw6sch:"Thời gian biểu IPv6",
	tunnel6:"Đường hầm IPv6",
	qos:"Chất lượng dịch vụ",
	qosbasic:"Cài đặt cơ bản",
	qoslist:"Cài đặt SP/WRR",
	tclist:"Điều khiển dải tần",
	tc:"Điều khiển dải tần",
	arp:"Kết hợp IP & MAC",
	arpbind:"Cài đặt liên kết",
	arplist:"Danh sách ARP",
	ddns:"DNS động",
	diag:"Chẩn đoán",
	tools:"Công cụ hệ thống",
	log:"Bản ghi hệ thống",
	time:"Cài đặt thời gian",
	mcl:"Mật mã",
	ipv6:"IPv6",
	local:"Quản lý nội bộ",
	Remote:"Quản lý từ xa",
	cwmp:"Thiết lập CWMP",
	snmp:"Cài đặt SNMP",
	bnr:"Sao lưu & khôi phục",
	def:"Mặc định nhà sản xuất",
	softup:"Nâng cấp phần mềm",
	restart:"Khởi động lại  ",
	autoreboot:"Tự động khởi động lại",
	stat:"Số liệu thống kê",
	logout:"Đăng xuất"
};
var country_str = new Array(
	"Albania",
	"Algeria",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahrain",
	"Belarus",
	"Belgium",
	"Belize",
	"Bolivia",
	"Brazil",
	"Brunei Darussalam",
	"Bulgaria",
	"Canada",
	"Chile",
	"Trung Quốc",
	"Colombia",
	"Costa Rica",
	"Croatia",
	"Cyprus",
	"Czech Republic",
	"Đan Mạch",
	"Cộng hòa Dominican",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Estonia",
	"Finland",
	"France",
	"Georgia",
	"Germany",
	"Greece",
	"Guatemala",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"Ấn Độ",
	"Indonesia",
	"Iran",
	"Ireland",
	"Israel",
	"Ý",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"North Korea",
	"Korea Republic",
	"Kuwait",
	"Latvia",
	"Lebanon",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macau",
	"Macedonia",
	"Malaysia",
	"Malta",
	"Mexico",
	"Monaco",
	"Morocco",
	"Netherlands",
	"New Zealand",
	"Norway",
	"Oman",
	"Pakistan",
	"Panama",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Romania",
	"Russia",
	"Saudi Arabia",
	"Singapore",
	"Serbia",
	"Cộng hòa Slovak",
	"Slovenia",
	"South Africa",
	"Spain",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Thailand",
	"Trinidad And Tobago",
	"Tunisia",
	"Turkey",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Venezuela",
	"Viet Nam",
	"Yemen",
	"Zimbabwe"
);

//voip
var vline = new Array (
	"Chuyển tiếp số vô điều kiện",
	"Chuyển tiếp khi  \"bận\" số",
	"Chuyển tiếp khi  \"không trả lời\" số"
);
var aemerg = new Array (
	"Tiền tố của cuộc gọi khẩn cấp 1, xung đột với Kế hoạch quay số!",
	"Tiền tố của cuộc gọi khẩn cấp 2, xung đột với Kế hoạch quay số!",
	"Tiền tố của cuộc gọi khẩn cấp 3, xung đột với Kế hoạch quay số!",
	"Tiền tố của cuộc gọi khẩn cấp 4, xung đột với Kế hoạch quay số!",
	"Tiền tố của cuộc gọi khẩn cấp 5, xung đột với Kế hoạch quay số!",
	"Tiền tố của cuộc gọi khẩn cấp 1, xung đột với một cuộc gọi khẩn cấp khác!",
	"Tiền tố của cuộc gọi khẩn cấp 2, xung đột với một cuộc gọi khẩn cấp khác!",
	"Tiền tố của cuộc gọi khẩn cấp 3, xung đột với một cuộc gọi khẩn cấp khác!",
	"Tiền tố của cuộc gọi khẩn cấp 4, xung đột với một cuộc gọi khẩn cấp khác!",
	"Tiền tố của cuộc gọi khẩn cấp 5, xung đột với một cuộc gọi khẩn cấp khác!"
);
var aline1 = new Array (
	"Vui lòng nhập một số PSTN hợp lệ cho trường Số chuyển tiếp không điều kiện (không phải địa chỉ IP)!",
	"Vui lòng nhập một số PSTN hợp lệ cho trường Số chuyển tiếp khi bận (không phải địa chỉ IP)!",
	"Vui lòng nhập một số PSTN hợp lệ cho trường Số chuyển tiếp khi không trả lời (không phải địa chỉ IP)!",
	"Vui lòng nhập một địa chỉ IP hợp lệ cho trường Số chuyển tiếp không điều kiện.",
	"Vui lòng nhập một địa chỉ IP hợp lệ tại trường Chuyển tiếp khi bận.",
	"Vui lòng nhập một địa chỉ IP hợp lệ cho trường Số chuyển tiếp khi không trả lời."
);
var aline2 = new Array (
	"Vui lòng nhập một số PSTN hợp lệ cho số 1 (không phải địa chỉ IP)!",
	"Vui lòng nhập một số PSTN hợp lệ cho số 2 (không phải địa chỉ IP)!",
	"Vui lòng nhập một số PSTN hợp lệ cho số 3 (không phải địa chỉ IP)!",
	"Vui lòng nhập một số PSTN hợp lệ cho số 4 (không phải địa chỉ IP)!",
	"Vui lòng nhập một số PSTN hợp lệ cho số 5 (không phải địa chỉ IP)!",
	"Vui lòng nhập một địa chỉ IP hợp lệ cho Số 1.",
	"Vui lòng nhập một địa chỉ IP hợp lệ cho Số 2.",
	"Vui lòng nhập một địa chỉ IP hợp lệ cho Số 3.",
	"Vui lòng nhập một địa chỉ IP hợp lệ cho Số 4.",
	"Vui lòng nhập một địa chỉ IP hợp lệ cho Số 5."
);
 
// In "m_str", most of the words are from the button. Some are used to display the stat or the result. 
var m_str =
{
	action:"Hoạt động",
	add: "Thêm vào",
	addnew: "Thêm mới",
	del: "Xóa",
	view: "Lượt xem",
	edit: "Chỉnh sửa",
	set:"Đặt",
	save: "Lưu",
	apply:"Ứng dụng",
	back: "Trở về",
	next: "Tiếp theo",
	help: "trợ giúp",
	reload: "Tải lại",
	refresh: "Làm mới",
	start: "Bắt đầu",
	stop: "Dừng",
	conn: "Kết nối",
	disconn: "Ngắt kết nối",
	renew: "Thay mới",
	release: "Thoát ra",
	en: "Kích hoạt",
	dis: "vô hiệu hóa",
	enall: "Kích hoạt tất cả",
	disall: "vô hiệu hóa tất cả",
	delall: "Xóa tất cả",
	ensel: "Cho phép chọn",
	dissel: "vô hiệu hóa các mục đã chọn",
	delsel: "Xóa mục đã chọn",
	allow: "Cho phép",
	deny: "Từ chối",
	finish:"Kết thúc ",
	reboot:"Khởi động lại  ",
	quit: "Thoát",
	bound:"Giới hạn",
	unbound:"Tháo ra ",
	enabled: "Bật",
	disabled: "đã vô hiệu hóa",
	loaded:"Đã tải",
	unloaded:"Không tải",
	initing: "Thiết lập ban đầu",
	obtaining: "Đạt được",
	connected: "Đã kết nối",
	connecting: "Đang kết nối",
	disconnected: "Đã ngắt kết nối",
	auto: "Tự động",
	unknown: "Không nhận ra  ",
	none: "Không",
	err: "Lỗi",
	warn:"Cảnh báo",
	note:"Lưu ý",
	errno: "Mật mã lỗi",
	success: "Thành công",
	pass:"Truyền qua",
	skip:"Bước nhảy",
	fail: "Không thành công",
	enWlsIptv:"Kích hoạt tính năng kết nối không dây cho IPTV",
	remove:"Xóa",
	selectall:"Chọn tất cả",
	unselectall:"Bỏ chọn tất cả",
	yes:"Đồng ý",
	config:"Cấu hình",
	bannermodel:"Số model:",
	unplugged:"Tháo đầu cắm",
	identifying:"đang nhận dạng",
	identified:"Xác định thành công",
	detecting: "Đang dò…",
	note: "Lưu ý",
	detect: "Dò",
	reset: "Đặt lại",
	upperFolder: "phía trên",
	def: "Mặc định"
};
// In "c_str", all strings are from the confirm window
var c_str =
{
	chgmod:"Việc thay đổi chế độ hoạt động sẽ không có hiệu lực cho đến khi router khởi động lại. Bạn có muốn thay đổi chế độ hoạt động?",
	creboot: "Thiết bị sẽ khởi động lại . Bạn có muốn tiếp tục không?",
	cdefaults: "Tất cả các cấu hình hiện tại sẽ bị mất khi phục hồi Router. Bạn có muốn tiếp tục không?",
	del_con: "Bạn có chắc chắn muốn xóa giao diện này?",
	save_reboot: "Thiết bị phải khởi động lại máy để các thay đổi có hiệu lực. Bạn có muốn tiếp tục không?",
	dslcfg_ask:"Bấm OK sẽ gây ra ngắt kết nối. Bạn có muốn tiếp tục không?",
	lancfg_ask:"Tùy chỉnh địa chỉ IP LAN hoặc subnet mask sẽ yêu cầu bạn đăng nhập lại. Bạn cũng có thể sẽ không thể truy cập router từ máy tính này. Bạn có muốn tiếp tục?",
	refresh: "Trang web sẽ làm mới. Bạn có muốn tiếp tục không?",
	refresh_dis:"Trang này sẽ làm mới và có thể gây ra ngắt kết nối. Bạn có muốn tiếp tục không?",
	ftp_vs_conflict:"Cổng xung đột với máy chủ ảo có sẵn. Bấm chọn OK để vô hiệu hóa mục máy chủ ảo liên quan và tiếp tục. Bấm chọn hủy để sử dụng một cổng khác nhằm tránh xung đột này.",
	ftp_pt_conflict:"Cổng xung đột với cổng cảnh báo có sẵn. Bấm chọn OK để vô hiệu hóa mục Cổng cảnh báo liên quan và tiếp tục. Bấm chọn hủy để sử dụng một cổng khác nhằm tránh xung đột này.",
	ftp_upnp_conflict:"Cổng xung đột với UPnP. Bấm chọn OK để xóa mục UPnP liên quan và tiếp tục. Bấm chọn hủy để sử dụng một cổng khác nhằm tránh xung đột này.",
	ftp_dmz_conflict:"xung đột chức năng  với máy chủ DMZ. Nhấn OK để vô hiệu hóa máy chủ DMZ và tiếp tục.",
	forwarding_ftp_conflict:"Xung đột truy cập Internet của máy chủ FTP USB. Xin vui lòng bấm OK để vô hiệu hóa truy cập Internet của máy chủ FTP USB và cho phép các yêu cầu chuyển tiếp về cổng  cần thiết.",
	qos_del_queue:"Một khi hàng đợi đã bị xóa, tất cả phân loại liên quan đến hàng đợi sẽ bị xóa. Bạn có chắc chắn muốn xóa hàng đợi này không?",
	usb3g_del_all:"Bạn có chắc chắn muốn xóa tất cả các tập tin cấu hình USB?",
	voice_dialplan:"Dial Plan không thể được thêm vào nếu không có một tài khoản đã tồn tại, bạn muốn thêm một tài khoản?",
	lan_reboot:"Tùy chỉnh địa chỉ IP LAN hoặc Subnet Mask sẽ có hiệu lực sau khi khởi động lại, bấm chọn OK để khởi động lại router ngay.",
	logout:"Bạn có chắc chắn đăng xuất?",
	qs_unplugged: "Dây cáp đã bị tháo.\nTrước khi tiếp tục, vui lòng đảm bảo dây cáp kết nối đến cổng WAN của thiết bị đã được kết nối đúng.",
	qs_selectOpt: "Vui lòng chọn một tùy chọn!",
	wl_region_warn: "Chọn sai quốc gia có thể gây nhiễu cho các thiết bị khác và vi phạm pháp luật hiện hành."
};
// In "s_str", strings are complex. Most of them appear more than once. Some form long button. Some used by Javascript. 
var s_str =
{
	timeout: "Thời gian nghỉ",
	schedule: "Thời gian biểu",
	autoReboot:"Tự động khởi động lại",
	everyday:"Tất cả các ngày&nbsp;&nbsp;",
	sel_day:"Chọn ngày",
	hourmin:"Giờ:Phút",
	retime: "Thời gian còn lại:",
	scheduleDisable:"Chức năng Tự động khởi động lại chưa có hiệu lực,<br/>vui lòng kiểm tra mục Cài đặt thời gian.",
	scheduleEnable:"Chức năng Tự động khởi động lại đã có hiệu lực.",
	index:"Tốc độ",
	status:"Trạng thái",
	desc:"Mô tả",
	conntype:"Loại kết nối",		
	ipmask:"IP/Mask",
	bridge:"Bridge",
	dynip:"IP động",
	staip:"IP tĩnh",
	macaddr:"Địa chỉ MAC",
	ipaddr:"Địa chỉ IP",
	internetipaddr:"Địa chỉ IP Internet",
	netmask:"Subnet Mask",
	gateway:"Cổng",
	defgw:"Cổng mặc định",
	dns:"Máy chủ DNS",
	internetdns:"DNS Internet",
	primarydns:"Máy chủ DNS chính",
	secdns:"Máy chủ DNS thứ cấp",
	group:"Nhóm",
	intf:"Giao diện   ",
	port: "Cổng",
	proto:"Giao thức",
	operation:"Hoạt động",
	atm:"Cấu hình ATM",
	encapmod:"Chế độ bao đóng ",
	atmqos:"ATM QoS Type",
	fps:"khung",		
	pps:"gói tin/giây",
	optional:"(tùy chọn)",		
	recom:"(Khuyến nghị)",
	service:"Dịch vụ cài đặt mạng WAN",
	username:"Tên người dùng",
	passwd:"Mật mã",
	secondConn:"Kết nối thứ cấp",
	pppusr:"Tên đăng nhập PPP",		
	ppppwd:"Mật mã PPP",		
	cfmpwd:"Xác nhận mật mã",
	unicast:"Nhận địa chỉ  với Unicast",
	noreq:"(Thường không yêu cầu)",
	srvname:"Tên dịch vụ:",
	acname:"Tên máy chủ:",
	midle:"Thời gian nghỉ tối đa:",
	minutes:"Phút ",
	seconds:"giây",
	pkts:"Gói tin ",
	bytes:"Bytes",
	zmean:"(0 ý nghĩa kết nối vẫn hoạt động tại mọi thời điểm)",
	connmode:"Chế độ kết nối:",
	typedemand:"Kết nối theo yêu cầu",
	typeauto:"Luôn luôn",
	typemanual:"Kết nối bằng tay",
	authtype:"Kiểu xác thực",
	cur_con: "Kết nối hiện tại",		
	ennat:"Kích hoạt NAT",
	enfullcone:"Kích hoạt tính năng Fullcone NAT",
	enspi:"Kích hoạt tính năng tường lửa SPI",
	enigmp:"Kích hoạt IGMP Proxy",
	/*add by wanghao*/
	igmpversion:"Phiên bản IGMP.",
	igmpv2:"v2",
	igmpv3:"v3",
	/*add end*/
	mtu1480:"1480 như mặc định",
	mtu1500:"1500 như mặc định",
	mtu1460:"1460 như mặc định",
	mtu1420:"1420 như mặc định",
	nochg:"không thay đổi trừ khi cần thiết",
	dnsmanual:"Cài đặt máy chủ DNS thủ công",
	hostname:"Host Name",
	echo:"Khoảng thời gian yêu cầu Echo",
	echoinfo:"(0-120 giây, 0 nghĩa không có yêu cầu)",
	useispaddr:"Sử dụng địa chỉ IP được chỉ định bởi ISP",
	ispaddr:"Địa chỉ IP ISP xác định",
	option:"Lựa chọn",
	resume_mac:"Khôi phục máy MAC",
	rebooting:"Đang khởi động lại  ",
	uploading:"Đang tải lên",
	upgrading:"Đang nâng cấp",
	wait_reboot:"Hệ thống được khởi động lại. Xin vui lòng chờ ...",
	wait_upload:"Đang tải lên. Xin vui lòng chờ ...",
	wait_restore:"Vui lòng đợi, cấu hình sẽ có tác dụng sau khi thiết bị khởi động lại...",
	wait_upgrade:"After the upgrade, please wait fhoặc the device to reboot…",
	wl:"Mạng không dây ",
	wl2g:"Mạng không dây ",
	wl5g:"Mạng không dây 5GHz",
	wlname:"Tên mạng không dây",
	ssid:"(Còn được gọi là SSID)",
	permanent: "Dài hạn",
	region:"Vùng",
	wl11b:"chỉ 11b",
	wl11bg:"trộn 11bg",
	wl11g:"chỉ 11g",
	wl11n:"chỉ 11n",
	wl11bgn:"trộn 11bgn",
	wl11a:"chỉ 11a",
	wl11an:"trộn 11an",
	wl11ac:"trộn 11a/n/ac",
	channel: "kênh truyền",
	mode:"Chế độ  ",
	chnwidth:"Độ rộng kênh truyền",
	encryption:"Mã hóa",
	security:"Bảo mật",
	wlsec:"Bảo mật",
	wldissec:"vô hiệu hóa bảo mật không dây",
	wpaPersonal: "WPA/WPA2 - Người dùng cá nhân",
	wpaEnterprise: "WPA/WPA2 - Doanh nghiệp",
	opensys:"Hệ thống mở",
	sharekey:"Chìa khóa chung",
	key:"Mã",
	keytype:"Dạng mã",
	wlpwd:"Mật mã mạng không dây",
	pskpwdwarn:"(Nhập ký tự ASCII khoảng giữa 8 và 63 hoặc ký tự thập lục phân khoảng giữa 8 và 64)",
	qss_ok:"Thiết bị đã được thêm thành công!",
	qss_fail:"Không thêm các thiết bị!",
	associated:"Đã kết hợp",
	faccess:"Truy cập đầy đủ",
	ronly:"Chỉ đọc",
	naccess:"Không truy cập",
	standby:"Dự phòng",
	online:"Trực tuyến",
	offline:"Ngoại tuyến",
	active1:"Hoạt động",
	inactive:"Không hoạt động",
	not_vailable:"Không tồn tại  ",
	newfld:"Thêm thư mục mới",
	browse:"Duyệt",
	hide:"Ấn đi",
	disk:"Đĩa",
	activate:"Kích hoạt",
	deactivate:"Tắt",
	volume:"Volume",
	filesys:"Hệ thống tập tin",
	capacity:"Dung lượng",
	both:"Cả hai",
	active:"Hoạt động",
	passive:"Bị động",
	all:"Tất cả",
	any_host:"Bất kỳ máy chủ",
	any_time:"Mọi lúc",
	time:"Thời gian",
	sun:"Sun.",
	mon:"Mon.",
	tues:"Tues.",
	wed:"Wed.",
	thur:"Thur.",
	fri:"Fri.",
	sat:"Sat.",
	last:"Cuối",
	list_blank:"Danh sách hiện tại trống ",
	max:"Tối đa",
	min:"Tối thiểu",
	reset_all:"Đặt lại tất cả",
	getgmt: "Lấy giờ GMT…",
	getGmt2:"Nhận giờ GMT",
	getPcTime:"Lấy từ máy tính",
	gmtfail: "Nhận giờ GMT thất bại",		
	scheduleTip:"Thời gian biểu dựa trên thời gian của Router. Thời gian có thể được thiết lập trong \"Công cụ hệ thống ->",
	rebootscheduleTip:"Thời gian biểu dựa trên thời gian của Router.<br/>Thời gian có thể được thiết lập trong \"Công cụ hệ thống ->",
	timeSet:"Cài đặt thời gian",		
	auth_fail:"Quá trình xác thực thất bại",		
	wrong_domain:"Tên miền không hợp lệ",
	standard_user:"Người dùng chuẩn",
	advanced_user:"Người dùng nâng cao",
	diag_end:"Hoàn thành chẩn đoán",
	diag_pause:"Tạm ngưng chẩn đoán",
	diag_dsl:"Kiểm tra đồng bộ hóa xDSL",
	diag_ppp:"Kiểm tra kết nối máy chủ PPP",
	diag_auth:"Kiểm tra sự xác nhận với ISP",
	diag_ip:"Kiểm tra địa chỉ IP được gán",
	diag_dhcp:"Kiểm tra kết nối của máy chủ DHCP ",
	diag_gw:"Ping gateway mặc định",
	diag_dns:"Ping máy chủ tên miền chính",
	diag_root:"Kiểm tra thử nghiệm DNS",
	diag_ncsi:"Kiểm tra trạng thái kết nối mạng (NCSI)",
	diag_surf:"Kiểm tra trình duyệt internet",
	no_internet:"Không tìm thấy Internet tham gia vào",
	no_wan:"Giao diện WAN không được cấu hình!",
	emerg:"Khẩn cấp",
	alert:"Alert",
	crit:"Giới hạn",
	notice:"Thông báo ",
	info:"Thông tin",
	debug:"Kiểm tra sửa lỗi",
	
	ip4en:"Kích hoạt IPv4",
	ip6en:"Kích hoạt IPv6",
	ip6addr:"Địa chỉ IPv6  ",
	plen:"Chiều dài tiền tố",
	ip6gw:"Cổng IPv6  ",
	ip6dns:"Máy chủ DNS IPv6",
	ip6secdns:"Máy chủ DNS IPv6 thứ cấp",
	ip6defgw:"Gateway mặc định IPv6",
	ip6dnsmanual:"Cài đặt máy chủ DNS IPv6 thủ công",
	ip6useispaddr:"Sử dụng địa chỉ IPv6 chỉ định bởi ISP",
	ip6ispaddr:"Địa chỉ IPv6 ISP xác định",
	ip6ispgw:"Gateway IPv6 ISP xác định",
	ip6unicast:"Nhận địa chỉ IPv6 với Unicast",
	ip6addrconf:"Loại định địa chỉ",
	enmld:"Kích hoạt MLD Proxy",
	staip6:"IPv6 tĩnh",
	dynip6:"IPv6 động",
	wanconn:"Kết nối mạng WAN  ",

	en3gbackup:"Kích hoạt tính năng 3G như một giải pháp sao lưu cho việc truy cập Internet",
	loc3g:"Địa điểm",
	isp3g:"Mobile ISP",
	opmod:"Chế độ hoạt động",
	muanl_3g_apn:"Cài đặt Số quay, APN, Tên đăng nhập và Mật mã thủ công",
	dialnum3g:"Quay số",
	disconnecting:"Đang ngắt kết nối",
        srvIpName:"Địa  chỉ IP/Tên máy chủ",
	enSsidBrc:"Kích hoạt tính năng phát thanh SSID ",
	host:"Host",
	wlScheCtl:"(lịch trình điều khiển)",
	wlUsrCtl:"(kiểm soát người dùng)",

	locale:"Lựa chọn nơi diễn ra ",
	prof:"Tên tiểu sử",
	phone:"Số điện thoại/ID người dùng",
	registraraddr:"Địa chỉ đăng ký",
	registrarport:"Cổng đăng ký",
	auid:"ID xác thực",
	password:"Mật mã",
	sipproxy:"SIP Proxy",
	sipproxyport:"Cổng SIP Proxy",
	outboundproxy:"Outbound Proxy",
	outboundproxyport:"Cổng Outbound Proxy",
	label1:"Đăng ký qua Outbound Proxy",
	siplist:"Danh sách tài khoản SIP",
	sipaccount:"Thoại - Tài khoản SIP",
	blacklistconf:"Cấu hình danh sách đen",
	enterinfo:"Nhập một số với độ dài trong khoảng [3,16].",
	dialplan:"Dial Plan",
	dest:"Đích",
	maxchar:"(16 ký tự tối đa)",
	none:"Không",
	operate:"Hoạt động",
	phone1:"Điện thoại 1",
	phone2:"Điện thoại 2",
	pstn:"PSTN",
	forbiddencall:"Chặn cuộc gọi",
	num:"số",
	whitelist:"Cấu hình danh sách trắng",
	blacklist:"Danh sách đen",
	white:"Danh sách trắng",
	title2:"Tối đa 30 mục có thể được cấu hình.",
	id:"ID",
	calllog:"Nhật ký cuộc gọi",
	src:"Nguồn",
	dst:"Đích",
	type:"Loại ",
	process:"Quá trình",
	time:"Thời gian",
	calllogconf:"Cấu hình nhật ký cuộc gọi",
	usbvoicemail:"Cấu hình hộp thư thoại USB",
	usbmass:"Lưu trữ USB Mass ngắt kết nối!",
	noConfig:"Không tìm thấy định dạng tập tin thích hợp trong thiết bị lưu trữ USB.",
	uncond:"vô điều kiện",
	usbmailnote:"Vui lòng lưu ý cài đặt trước của bạn về",
	usbmailend:"trong trang thiết lập điện thoại đã bị vô hiệu hóa kể từ khi bạn đã bật kích hoạt hộp thư thoại USB.",
	usbmailendon:"trong trang thiết lập điện thoại đã bị vô hiệu hóa kể từ khi bạn đã bật kích hoạt trên hộp thư thoại USB.",
	nocondend:"không trả lời/không điều kiện",
	dialplan:"Dial Plan",
	callfirewall:"Tường lửa cuộc gọi",
	prefix:"Tiền tố",
	emergencycall:"Cài đặt cuộc gọi khẩn cấp(PSTN)",
	forbiddencall:"Chặn cuộc gọi",
	endwith:"Kết thúc với '#'",
	forwardun:"Chuyển tiếp vô điều kiện:",
	noanswer:"không trả lời",
	linenote:"trong trang thư thoại USB đã bị vô hiệu hóa kể từ khi bạn đã kích hoạt chuyển tiếp vào",
	number:"Số",
	speeddial:"Quay số tốc độ",
	usbvoicemail:"Hộp thư thoại USB  ",
	white:"Danh sách trắng",
	voiplan:"LAN",
	voipwan:"Bất kỳ mạng _WAN",
	voiproute:"IP_Định tuyến",
	voipbridge:"IP_Cầu nối",
	feature:"Tính năng mật mã",
	city1:"(GMT-12:00) Enewetak, Kwajalein",
	city2:"(GMT-11:00) Đảo Midway, Samoa",
	city3:"(GMT-10:00) Hawaii",
	city4:"(GMT-09:00) Alaska",
	city5:"(GMT-08:00) Giờ chuẩn Thái Bình Dương  (Mỹ & Canada); Tijuana",
	city6:"(GMT-07:00) Giờ chuẩn vùng núi (Mỹ & Canada); Arizona",
	city7:"(GMT-06:00) Giờ chuẩn vùng Trung (Mỹ & Canada); Trung Mỹ, Thành phố Mexico.",
	city8:"(GMT-05:00) Giờ chuẩn vùng Bắc (Mỹ & Canada); Bogota, Lima",
	city9:"(GMT-04:30) Caracas",
	city10:"(GMT-04:00) Atlantic Time (Canada); Santiago, Asuncion",
	city11:"(GMT-03:30) Newfoundland (Canada)",
	city12:"(GMT-03:00) Brasilia, Buenos Aires, Gehoặcgetown, Greenland",
	city13:"(GMT-02:00) Giữa Đại Tây Dương.",
	city14:"(GMT-01:00) Azhoặces, Đảo Cape Verde.",
	city15:"(GMT) Giờ chuẩn Greenwich: Dublin, Edinburgh, London, Lisbon",
	city16:"(GMT+01:00) Amsterdam, Berlin, Rome, Stockholm, Paris, Prague, Bratislava",
	city17:"(GMT+02:00) Cairo, Athens, Istanbul, Minsk, Jerusalem, Kiev, Chisinau",
	city18:"(GMT+03:00) Baghdad, Kuwait, Riyadh",
	city19:"(GMT+03:30) Tehran",
	city20:"(GMT+04:00) Abu Dhabi, Muscat, Baku, Tbilisi, Yerevan, Moscow, St.Petersburg",
	city21:"(GMT+04:30) Kabul",
	city22:"(GMT+05:00) Islamabad, Karachi, Tashkent",
	city23:"(GMT+05:30) Madras, Kolkata, Mumbai, New Delhi",
	city24:"(GMT+05:45) Katmandu",
	city25:"(GMT+06:00) Almaty, Astana, Dhaka, Ekaterinburg, Bishkek",
	city26:"(GMT+06:30) Rangoon",
	city27:"(GMT+07:00) Bangkok, Jakarta, Hà Nội, Novosibirsk",
	city28:"(GMT+08:00) Beijing, Chongqing, Urumchi, Hong Kong, Taipei, Kuala Lumpur, Perth",
	city29:"(GMT+09:00) Tokyo, Osaka, Sapphoặco, Seoul",
	city30:"(GMT+09:30) Darwin, Adelaide",
	city31:"(GMT+10:00) Brisbane, Guam, Canberra, Melbourne, Sydney, Yakutsk",
	city32:"(GMT+11:00) Magadan, Solomon Is., New Caledonia",
	city33:"(GMT+12:00) Fiji, Kamchatka Peninsula, Marshall Is., Wellington",
	city34:"(GMT+13:00) Nukualofa",
	Jan: "Jan",
	Feb: "Feb",
	Mar: "Mar",
	Apr: "Apr",
	May: "May",
	Jun: "Jun",
	Jul: "Jul",
	Aug: "Aug",
	Sep: "Sep",
	Oct: "Tháng 11",
	Nov: "Nov",
	Dec: "Dec",
	First: "Trước tiên",
	nd2: "2nd",
	rd3: "3rd",
	th4: "4th",
	Mon: "Mon",
	Tue: "Tue",
	Wed: "Wed",
	Thu: "Thu",
	Fri: "Fri",
	Sat: "Sat",
	Sun: "Sun",
	
	pppoe_ru: "PPPoE/Russia PPPoE",
	secConn: "Kết nối thứ cấp",
	forDual: "&nbsp;(Để truy cập kép)",
	restoreFmac: "Khôi phục máy MAC",
	cloneMac: "Sao chép địa chỉ MAC",
	wanmac: "Địa chỉ MAC mạng WAN",
	pcmac: "Địa chỉ MAC máy tính của bạn",
	addrType:"Loại định địa chỉ",
	days: "Ngày",
	tcp_udp: "TCP hoặc UDP",
	high: "Cao",
	medium: "Trung bình",
	low: "Thấp",	
	auto: "Tự động",
	dynip_1: "IP động (tùy chọn phổ biến nhất)",
	band: "Băng thông",
	servipname: "Địa  chỉ IP/Tên máy chủ",
	hours: "nhiều giờ",
	minutes_full: "Phút ",
	id: "ID",
	type6to4: "Đường hầm 6to4",
	noAvailIntf: "Không có giao diện khả dụng.",
	bpa_cable  : "Cáp BigPond"
};
// In "s_str", strings are from each WEB page. Most of them are used only once in all pages.
var n_str = 
{
	status:{
		et:"Trạng thái",
		t_devinfo:"Thông tin thiết bị",
		t_swver:"Phiên bản phần mềm:",
		t_hwver:"Phiên bản phần cứng:",
		t_uptime:"Thời gian hoạt động hệ thống:",
		t_link:"Trạng thái đường truyền:",
		t_dslmode:"Loại điều biến DSL:",
		t_annex:"Loại phụ lục:",
		t_up:"Luồng lên",
		t_down:"Luồng dữ liệu xuống",
		t_currate:"Tốc độ hiện tại",
		t_maxrate:"Tốc độ tối đa",
		t_snr:"Lượng dự trữ SNR",
		t_att:"Suy hao đường truyền",
		t_errs:"Lỗi",
		t_title:"Tên",
		t_radio:"Vô tuyền không dây:",
		t_radio5g:"Vô tuyền không dây:",
		t_name:"Tên (SSID):",
		t_name5g:"Tên (SSID):",
		t_tx1:"Tốc độ truyền tối đa:",
		t_wlwds:"Trạng thái WDS:",
		t_wlwds5g:"Trạng thái WDS:",
		t_wlSchedu:"Thời gian biểu:",
		t_tx2:"Tốc độ truyền tối đa",
		t_ip6title:"Tên",
		t_ip6addrplen:"Độ dài địa chỉ/tiền tố IPv6",
		t_lan6cfgtype:"Loại tự động cấu hình",
		t_wanip:"Địa chỉ IP:",
		t_mask:"Subnet Mask:",
		t_gateway:"Cổng mặc định:",
		t_dns:"Máy chủ DNS:",
		t_voice:"Thoại  ",
		t_online: "Thời gian trực tuyến",
		t_lan: "LAN",
		t_wan: "WAN",
		authFail: "Quá trình xác thực thất bại, tên đăng nhập hoặc mật mã không đúng."
	},
	qsStart:{
		et:"Cài đặt nhanh - Bắt đầu",
		t_note1:"Chạy Cài đặt nhanh để cấu hình Cài đặt kết nối internet và không dây theo cách thủ công.",
		t_note2:"Để tiếp tục, vui lòng nhấp vào nút tiếp theo.",
		t_note3:"Để thoát ra, xin vui lòng bấm vào nút Exit."
	},
	qsIptv:
	{
		t_et:"Cài đặt nhanh - IPTV",
		t_igmp_version:"Phiên bản IGMP",
		t_iptv_mode:"Mẫu",
		t_iptv_enable:"Kích hoạt IPTV"
	},
	qsDsl:{
		et:"Cài đặt nhanh - DSL",
		t_info1:"Please enter the VPI/VCI provided by your ISP(Internet Service Provider).",
		t_info2:"Hoặc bạn có thể kích hoạt Tự động phát hiện PVC.",
		t_auto:"Kích hoạt tính năng tự động phát hiện PVC"
	},
	qsType:{
		et1:"Cài đặt nhanh - Dạng kết nối ADSL",
		et2:"Cài đặt nhanh - Dạng kết nối WAN",
		t_info:"Vui lòng chọn dạng kết nối ISP của bạn cung cấp.",
		t_auto_info:"Để router tự động phát hiện dạng kết nối Internet do ISP của bạn cung cấp.",
		t_ppp_info1:"(Yêu cầu tên người dùng và mật mã cho PPP qua Ethernet)",
		t_ppp_info2:"Bạn có kết nối DSL và được kết nối thông qua PPPoE (kết nối băng thông rộng) trên máy tính của bạn hoặc router hiện có.",
		t_pppoa_info:"(Yêu cầu tên người dùng và mật mã cho PPP qua ATM)",
		t_dhcp_info1:"(Có được IP động từ ISP, còn gọi là IP động IPoE)",
		t_dhcp_info2:"Đối với kết nối cáp/ DSL/băng thông rộng  làm cho máy tính của bạn trực tuyến ngay lập tức mà không cần bất kỳ cài đặt hoặc đăng nhập.",
		t_staip_info1:"(Tự thiết lập địa chỉ IP tĩnh được cung cấp bởi ISP của bạn, cũng được gọi là IP tĩnh IPoE)",
		t_staip_info2:"ISP của bạn cung cấp cho bạn các thông số IP xác định.",
		t_ipoa_info:"(Tự thiết lập địa chỉ IP tĩnh được cung cấp bởi ISP của bạn, cũng được gọi là IP qua ATM)",
		t_br_info:"(Quay số từ máy tính và Router)",
		eoa_info:"Lưu ý: IPoA &amp; PPPoA không hỗ trợ nhiều kết nối trên một PVC. IPoA và PPPoA sẽ bị vô hiệu hóa đã tồn tại trong PVC này.",
		t_tip: "Cài đặt nhanh để chuẩn bị để thiết lập kết nối internet của bạn, xin vui lòng chọn một loại dưới đây phù hợp với ISP của bạn. Mô tả chi tiết sẽ được hiển thị sau khi bạn chọn các loại tương ứng.",
		t_autoDetect: "Tự động-dò",
		t_pppoe_ru: "PPPoE/Russia PPPoE",
		t_l2tp_ru: "L2TP/Russia L2TP ",
		t_pptp_ru: "PPTP/Russia PPTP ",
		t_note: "Lưu ý: Đối với người dùng ở một số khu vực (như Nga, Ukraine, vân vân..), vui lòng liên hệ ISP của bạn để chọn dạng kết nối theo cách thủ công.",
		t_l2tp_info1: "Với dạng này, bạn cần điền tên đăng nhập, mật mã và địa chỉ IP/tên miền của máy chủ VPN do ISP cung cấp. Tự động phát hiện không thể phát hiện dạng kết nối này.",
		t_pptp_info1: "Với dạng này, bạn cần điền tên đăng nhập, mật mã và địa chỉ IP/tên miền của máy chủ VPN do ISP cung cấp. Tự động phát hiện không thể phát hiện dạng kết nối này."
	},
	qsDetectErr: {
		t_reasons: "Router không phát hiện loại kết nối internet của bạn, có thể do những lý do sau:",
		t_reason1: "1. Các Router không có chu kỳ năng lượng.",
		t_reason1Detail: "Để giải quyết vấn đề này, xin vui lòng tắt và mở nguồn điện router của bạn và chờ 2 phút để hoàn thành khởi tạo của nó. Nếu router của bạn có một pin dự phòng, xin vui lòng tháo và lắp lại pin của nó.",
		t_reason2: "2. Các kết nối phần cứng sai.",
		t_reason2Detail: "Để giải quyết vấn đề này, xin vui lòng kiểm tra lại các cổng internet (cổng màu xanh) đã gắn hoàn toàn bằng cáp Ethernet từ router của bạn hoặc thiết bị mạng khác.",
		t_reason3: "3. ISP của bạn (Cung cấp dịch vụ Internet) gán một IP cố định (tĩnh) cho bạn.",
		t_reason3Detail: "Router không thể tự động phát hiện loại mạng đặc biệt hiếm như vậy, bạn cần phải nhập các thông số bằng tay.",
		t_options: "Chọn một tùy chọn bên dưới và bấm chọn Tiếp để tiến hành:",
		t_dhcp_info1: "Tôi sẽ khởi động lại router bây giờ, vui lòng đợi 2 phút và tiếp tục. Thông thường tác vụ này sẽ có thể giải quyết hầu hết các vấn đề.",
		t_macclone_info1: "Tôi đã khởi động lại router trước, bây giờ tôi sẽ cố gắng để sao chép địa chỉ MAC từ máy tính ban đầu của tôi.",
		t_staip_info1: "Đồng ý, ISP của tôi gán cho tôi một địa chỉ IP cố định."
	},
	qsPPP:{
		et:"Cài đặt nhanh - PPPoE",
		t_info:"Vui lòng nhập Tên đăng nhập và Mật mã. Nếu bạn không biết Tên đăng nhập/Mật mã, vui lòng liên hệ ISP.",
		t_secondConn: "Kết nối thứ cấp",
		t_forDual: "&nbsp;(Để truy cập kép)"
	},
	qsL2tp: {
		et: "Cài đặt nhanh - L2TP",
		t_info: "Vui lòng nhập Tên đăng nhập và Mật mã. Nếu bạn quên thông tin này, vui lòng liên hệ với ISP của bạn."
	},
	qsPptp: {
		et: "Cài đặt nhanh - PPTP",
		t_info: "Vui lòng nhập Tên đăng nhập và Mật mã. Nếu bạn quên thông tin này, vui lòng liên hệ với ISP của bạn."
	},
	qsStaIP:{
		et:"Cài đặt nhanh - IP Tĩnh",
		t_info:"Vui lòng nhập thông số cài đặt cơ bản do ISP của bạn cung cấp. Nếu bạn không biết thông số cài đặt, vui lòng liên hệ với ISP."
	},
	qsPPPoA:{
		et:"Cài đặt nhanh - PPPoA",
		t_info:"Vui lòng nhập Tên đăng nhập và Mật mã ADSL. Nếu bạn không biết Tên đăng nhập/Mật mã, vui lòng liên hệ ISP."
	},
	qsIPoA:{
		et:"Cài đặt nhanh - IPoA",
		t_info:"Vui lòng nhập thông số cài đặt cơ bản do ISP của bạn cung cấp. Nếu bạn không biết thông số cài đặt, vui lòng liên hệ với ISP."
	},
	qs3g:{
		et:"Cài đặt nhanh - 3G",
		t_info:"3G có thể được thiết lập như là một phương pháp sao lưu cho truy cập Internet. Nếu bạn không muốn cài đặt cấu hình 3G hiện nay, nhấn Tiếp theo và tiếp tục. Nếu không, cho phép sao lưu 3G để áp dụng các cấu hình.",
		t_no_isp_start:"Nếu vị trí hoặc ISP của bạn không được liệt kê, hoặc số điện thoại cố định cần phải được cập nhật, vui lòng kích hoạt thiết lập cấu hình bằng tay.",
		t_no_isp_end:"và điền vào đúng chỗ"
	},
	qsAuto: {
		et: "Cài đặt nhanh - Tự động",
		t_detect: "Đang dò kiểu kết nối ISP của bạn cung cấp, xin vui lòng chờ …"
	},
	qsMacClone: {
		et: "Cài đặt nhanh - Sao MAC",
		t_mac_tip: "Địa chỉ MAC (Media Access Control) là định danh duy nhất để xác định máy tính hoặc thiết bị của bạn trên hệ thống mạng. Một số ISP có thể đăng ký địa chỉ MAC của máy tính mà bạn sử dụng để kết nối đến hệ thống của họ trong lần đầu tiên, và không cho phép bất cứ máy tính hoặc router nào khác kết nối Internet. Router TP-Link có thể giúp bạn \"sao chép\" địa chỉ MAC đã được đăng ký bới máy tính đầu tiên.",
		t_suggestion: "Trong hầu hết trường hợp, bạn không cần sao địa chỉ MAC. Nhưng nếu bạn không có kết nối Internet sau khi đã thực hiện Cài đặt nhanh, vui lòng thực hiện lại Cài đặt nhanh và thử sao địa chỉ MAC.",
		t_noClone: "Không, tôi KHÔNG cần sao địa chỉ MAC.",
		t_yesClone: "Đồng ý, tôi cần phải sao chép địa chỉ MAC.",
		t_makeSureNote: "Lưu ý: Vui lòng đảm bảo máy tính hiện tại của bạn là máy tính kết nối đến router hoặc thiết bị của ISP lúc đầu."
	},
	qsBandSelect: {
		et: "Cài đặt nhanh - Chọn băng tần kép không dây",
		t_note: "Vui lòng chọn hoặc xóa hộp chọn để kích hoạt hoặc vô hiệu hóa tần số vô tuyến được đề xuất."
	},
	qsWl:{
		et:"Cài đặt nhanh - Không dây",
		et_2g:"Cài đặt nhanh - Không dây",
		t_more: "Thêm cài đặt không dây nâng cao"
	},
	qsWl5G:{
		et:"Cài đặt nhanh - Không dây 5GHz",
		t_more: "Thêm cài đặt không dây nâng cao"
	},
	qsSave:{
		et:"Cài đặt nhanh - Xác nhận",		
		t_info:"Cài đặt nhanh hoàn tất. Vui lòng xác nhận tất cả các thông số dưới đây. Nhấn trở lại để sửa đổi bất kỳ cài đặt hoặc bấm lưu để lưu và áp dụng các cấu hình của bạn.",		
		t_summary:"Tổng thông số:",
		t_note:"Lưu ý: Một số kết nối sẽ bị xóa."
	},
	qsEnd:{
		et:"Cài đặt nhanh - Hoàn tất",		
		t_stat:"Trạng thái cài đặt:",
		t_mode:"Cấu hình chế độ hoạt động:",
		t_pvc:"Phát hiện PVC:",
		t_release:"Kết nối mạng WAN ngắt:",
		t_wan:"Cấu hình kết nối WAN:",
		t_gw:"Cấu hình cổng và DNS :",
		t_wl:"Cấu hình Wi-Fi",
        t_wl2g:"Cấu hình mạng không dây 2.4GHz",
		t_wl5g:"Cấu hình mạng không dây 5GHz",
		t_iptv:"Cấu hình IPTV:",
		t_fail:"Tự động phát hiện PVC thất bại. Vui lòng nhập tham số PVC của ISP của bạn và bấm chọn TIẾP. Nếu bạn không rõ tham số PVC, xin vui lòng liên hệ với ISP của bạn để biết thêm thông tin.",
		con_end1:"Cài đặt nhanh đã hoàn tất. Vui lòng bấm HOÀN TẤT để thoát.",
		con_end2:"Cài đặt nhanh đã hoàn tất! Cấu hình sẽ không có hiệu lực cho đến khi thiết bị khởi động lại. Vui lòng bấm KHỞI ĐỘNG LẠI để khởi động lại Router.",
		con_end3:"Lưu ý: Nếu Router vẫn không thể kết nối Internet, vui lòng chọn trình đơn \"Mạng > WAN\" ở phía bên trái để xác nhận dạng và chế độ kết nối WAN tại trang WAN.",
		t_retry:"Một số cấu hình trong quá trình cài đặt nhanh có thể đã bị mất. Vui lòng thử lại.",
		t_def:"Nếu lỗi xuất hiện trở lại hoặc vẫn không có kết nối Internet, hãy khôi phục lại Router về mặc định của hãng và thử khôi phục nhanh một lần nữa."
	},
	qsVoiceAcc:{
		t_et:"Cài đặt nhanh - Thoại",
		t_info1:"Các \"kiểu WAN\" được thiết lập để \"Bắt cầu\", giọng nói không được hỗ trợ.",
		t_info2:"các thông số cơ bản bằng giọng nói có thể được cấu hình trên trang này. Để bỏ qua cấu hình VoIP, để \"Tên hồ sơ\" trống và bấm vào nút \"Tiếp theo\".",
		t_con_haveUVM:"Lưu ý: Xin vui lòng thiết lập các thư thoại USB trong \"Voice>USB Voicemail\" hoặc sử dụng đĩa CD để hỗ trợ cài đặt dễ dàng.",
		t_setup:"Cài đặt nâng cao "
	},
	sysMode:{
		et1:"Chế độ hoạt động",
		et2:"Cài đặt nhanh - Chế độ hoạt động",
		t_mode:"Chọn một Chế độ hoạt động:",
		sysmod1:"Chế độ ADSL Modem Router ",
		sysmod2:"Chế độ router không dây",
		sysmod3:"Chế độ Router"
	},
	wan:
	{
		et:"Giao diệnADSL WAN",
		t_info:"Trang này hiển thị thông tin của toàn bộ ADSL giao diện WAN.",		
		t_name:"Tên",
		t_type:"Loại "
	},
	div:
	{
		et:"Cài đặt WAN",
		t_autoPvc:"Kích hoạt tính năng tự động phát hiện PVC",
		t_note1:"Chú ý: PVC hiện tại có vài kết nối, các thông số sau sẽ không cho phép thay đổi!",
		t_note2:"Chú ý: Vui lòng không thay đổi các thông số bên dưới trừ trường hợp cần thiết!",
		t_speDial:"Quay số đặc biệt:"
	},
	ethWan:{
		et:"Cài đặt WAN",		
		t_en:"Bật tính năng kết nối WAN",
		t_addrType:"Loại định địa chỉ:",
		auto_auth: "Tự động_xác thực",
		t_bpa_authServer: "Máy chủ chính thức:",
		t_bpa_authDomain: "Miền chính thức:",
		authFail: "Quá trình xác thực thất bại, tên đăng nhập hoặc mật mã không đúng."
	},
	usb3g:{
		et:"Cài đặt 3G  ",
		t_info_start:"Cài đặt 3G là không khả dụng do chế độ hoạt động không được thiết lập để chế độ 3G Router hoặc sao lưu 3G không được kích hoạt. Xin vui lòng",
		t_info_en:"Kích hoạt tính năng sao lưu 3G",
		t_info_chg:"hoặc thay đổi cài đặt",
		t_info_end:"để sửa đổi bất kỳ cài đặt cấu hình 3G.",
		t_backup_delay_time:"Trì hoãn sao lưu",
		t_revert_delay_time:"Trì hoãn trở lại nguyên thể",
		t_3g_modem:"USB 3G modem",
		t_pin_status:"Trạng thái PIN",
		card_name_unplugged:"Tháo đầu cắm",
		card_name_ing:"đang nhận dạng",
		card_name_ok:"Xác định thành công",
		pin_status_fail:"Không thể kết nối chữ viết",
		pin_status_ready:"Sẵn sàng",
		pin_status_pin:"PIN đã khóa",
		pin_status_puk:"Khóa PUK",
		pin_status_errror:"Lỗi không xác định",
		t_pin_code:"Mã PIN",
		pinUnlockBtn:"Mở khóa",
		t_notice_t:"Thông báo ",
		t_notice:"Bạn phải thiết lập quay số và APN bằng tay, hãy bấm vào Nâng cap để sửa đổi các cấu hình.",
		t_sysmode_start:"Hiện tại",
		t_sysmod_is:"là",
		sysmod_dsl:"Chế độ ADSL Modem Router ",
		sysmod_eth:"Chế độ router không dây",
		t_sysmod_end:"Chế độ kết nối và thời gian nhàn rỗi tối đa không thể cài đặt bằng tay.",
		t_pin_chg_en:"Kích hoạt thay đổi mã PIN",
		t_old_pin:"Mã PIN cũ",
		t_new_pin1:"Mã PIN mới",
		t_new_pin2:"Xác nhận mã PIN mới ",
		t_mtu:"Kích thước MTU (byte)",
		t_mtu1480:"(Mặc định là 1480, không thay đổi trừ khi cần thiết)",
		t_follow_ip:"Sử dụng địa chỉ IP dưới đây",
		t_static_ip:"Địa chỉ IP tĩnh",
		t_follow_dns:"Sử dụng các máy chủ DNS sau",
		t_pri_dns:"DNS chính",
		t_sec_dns:"DNS thứ cấp"
	},
	usb3gModemList:{
		et:"Cài đặt Modem 3G USB",
		t_id:"ID",
		t_vendor:"Nhà cung cấp",
		t_model:"Model"
	},
	usb3gUpload:{
		et:"Tập tin cấu hình Modem USB 3G tải lên",
		t_file:"Tập tin",
		t_info:"Vui lòng lưu ý: Nếu bạn khôi phục cài đặt  gốc cho thiết bị, tập tin bin sẽ bị mất. Trong trường hợp bạn bị mất tập tin bin, bạn sẽ cần phải tải nó lên lại, hoặc tải về firmware mới nhất của chúng tôi từ",
		t_info2:"Phần mền đã được cập nhật sẽ được cài đặt vào thiết bị 3G của bạn và khôi phục tất cả các tính năng của nó.",
		upload:"Tải lên",
		back:"Trở về"
	},
	hw_nat:{
		et:"Cài đặt Kiểm soát NAT",
		t_hwnat:"Trạng thái phần cứng NAT hiện tại:",
		t_softnat:"Trạng thái NAT hiện tại:",
		t_note:"1. Hãy chắc chắn rằng NAT được kích hoạt nếu bạn muốn cấu hình phần cứng NAT hoạt động.",
		t_tcEn:"2. Nếu Kiểm soát băng thông được kích hoạt, phần cứng NAT sẽ không hoạt động, vì hai mô-đun không thể làm việc cùng một lúc."
	},
	group:{
		et:"Giao diện nhóm",
		t_info:"Trang này hiển thị tất cả các nhóm hiện tại.",
		t_wancon:"Giao diện WAN  ",
		t_lancon:"Giao diện LAN",
		t_note1:"Lưu ý: Bạn không thể vô hiệu hóa tính năng VLAN khi Kết nối IPTV hoặc WAN Ethernet đã được kích hoạt.",
		t_note2:"Lưu ý: Bạn không thể vô hiệu hóa tính năng VLAN khi Kết nối WAN Ethernet đã được kích hoạt.",
		t_note3:"Lưu ý: Bạn không thể di chuyển gateway mặc định đến một nhóm khác.",
		t_note4:"Kích hoạt các cổng LAN ảo đặc trưng"
	},
	groupAdd:{
		et:"Thêm nhóm mới",
		t_name:"Tên nhóm:",
		t_lan:"Mạng LAN có sẵn",
		t_added:"Thêm giao diện",
		t_wan:"Mạng WAN có sẵn",
		t_note1:"Lưu ý: Bạn không thể di chuyển gateway mặc định",
		t_note2:"Đến nhóm khác"
	},
	lan:
	{
		et:"Cài đặt LAN",
		t_info:"Trang này hiển thị các thông tin về các giao diện mạng LAN.",
		t_pool:"Vùng dự trữ DHCP"
	},
	lanEdit:
	{
		et:"Cài đặt LAN",
		t_info:"Các thông số của mạng LAN có thể được cấu hình trên trang này.",
		t_note:"Lưu ý: Nếu địa chỉ IP LAN hoặc subnet mask đã bị thay đổi, vui lòng đảm bảo dãi địa chỉ DHCP và bất cứ địa chỉ IP tĩnh trong mạng nằm cùng lớp mạng với IP LAN mới.",
		t_ensnoop:"Kích hoạt IGMP Snooping",
		t_ensecip:"Kích hoạt tính năng IP thứ hai ",
		t_dhcp:"Máy chủ DHCP:",
		t_relay:"Đặt lại DHCP",
		t_poolstart:"Địa chỉ IP bắt đầu:",
		t_poolend:"Kết thúc địa chỉ IP:",
		t_leasetime:"Thời gian đã đăng kí:",
		t_leaseval:"(1~2880 phút, giá trị mặc định là 120)",
		t_defdomain:"Miền mặc định:",
		t_remote:"Địa chỉ máy chủ từ xa:",
		t_relay_warn:"Lưu ý: Bạn phải vô hiệu hóa NAT của kết nối WAN, nếu không cấu hình DHCP Relay sẽ có thể không có hiệu lực!"
	},
	status6: {
		et: "Trạng thái IPv6",
		t_connType: "Loại kết nối",
		t_connStatus: "Tình trạng kết nối",
		t_ip6Addr: "Địa chỉ IPv6  ",
		t_ip6Gw: "Gateway mặc định IPv6",
		t_ip6Dns: "DNS IPv6 chính",
		t_ip6SecDns: "DNS IPv6 thứ cấp",
		t_lan6cfgtype: "Dạng địa chỉ IPv6",
		t_assint:      "Giao diện kết hợp",
		t_interface:  "Tên giao diện:"
	},
	ethWan6: {
		t_6to4: "Đường hầm 6to4",
		t_ppp_same_sess: "PPPoE cùng phiên với kết nối IPv4",
		t_dyn_hide_addr_config: "Chỉ sử dụng tiền tố delegation từ ISP cho LAN",
		t_ppp_hide_addr_config: "Chỉ sử dụng tiền tố delegation từ ISP cho LAN"
	},
	lan6:
	{
		et:"Cài đặt LAN IPv6",
		t_info:"Các thông số của IPv6 mạng LAN có thể được cấu hình trên trang này khi IPv6 được kích hoạt.",
		t_note:"Lưu ý: Chỉ có nhóm mặc định hỗ trợ IPv6 tại thời điểm này.",
		t_addrtype:"Địa chỉ kiểu Tự động- cấu hình",
		t_pfxtype:"Loại cấu hình tiền tố vị trí",
		t_radvd:"RADVD",
		t_rdnss:"Kích hoạt tính năng RDNSS",
		t_ula:"Kích hoạt tiền tố ULA",
		t_ulapfx:"ULA Prefix",
		t_ulaplen:"Chiều dài Prefix ULA",
		t_dhcp6s:"Máy chủ DHCPv6",
		t_startaddr:"Địa chỉ IPv6 bắt đầu",
		t_endaddr:"Kết thúc địa chỉ IPv6 ",
		t_lstime:"Thời gian đã đăng kí",
		t_lssec:"giây (Giá trị mặc định là 86400)",
		t_delegated:"Ủy nhiệm",
		t_static:"Tĩnh",
		t_wan:"Tiền tố đã ủy nhiệm kết nối WAN",
		t_pfx:"Tiền tố vị trí",
		t_plen:"Chiều dài tiền tố vị trí",
		t_cur_wan: "Tiền tố đã ủy nhiệm kết nối WAN"
	},
	macClone:{
		et:"Sao MAC",
		t_wan:"Kết nối mạng WAN  ",
		t_pcmac:"MAC của PC hiện tại",
		t_clone:"Sao chép đến MAC",
		t_note1:"Sao địa chỉ MAC có thể sẽ dẫn đến việc kết nối lại.",
		t_note2:"Nếu sao chép MAC đã được thực hiện, bất kỳ kết nối cầu chia sẻ các cấu hình VPI / VCI cùng với các kết nối khác có thể không hoạt động."
	},
	alg:{
		et:"Cài đặt ALG",
		t_vpn:"Mạng riêng ảo (VPN)",
		t_pptp:"PPTP Pass-through:",
		t_l2tp:"L2TP Pass-through:",
		t_ipsec:"IPSec Pass-through:",
		t_alg:"Cổng lớp ứng dụng (ALG)"
	},
	dslcfg:{
		et:"Thiết lập DSL",
		t_mode:"Loại điều biến DSL",
		t_auto:"Tự động đồng bộ",
		t_annex:"Loại phụ lục",
		t_enswap:"Kích hoạt tính năng Bit Swap",
		t_ensra:"Bật tính năng SRA"
	},
	dhcp:{
		et:"Máy chủ DHCP",
		t_info:"Trang này hiển thị tất cả các dịch vụ DHCP hiện tại và cũng cho phép bạn cấu hình dịch vụ DHCP bằng cách bấm vào chỉnh sửa.",
		t_pool:"Vùng dự trữ DHCP"
	},
	dhcpEdit:{
		et:"Thiết lập DHCP",
		t_info:"Trang này cho phép bạn thiết lập các thông số máy chủ DHCP cung cấp các cấu hình TCP / IP cho tất cả các thiết bị kết nối với thiết bị này trên mạng LAN.",
		t_dhcp:"Máy chủ DHCP:",
		t_relay:"Đặt lại DHCP",
		t_poolstart:"Địa chỉ IP bắt đầu:",
		t_poolend:"Kết thúc địa chỉ IP:",
		t_leasetime:"Thời gian đăng kí:",
		t_leaseval:"(1~2880 phút, giá trị mặc định là 120)",
		t_defdomain:"Miền mặc định:",
		t_remote:"Địa chỉ máy chủ từ xa:",
		t_relay_warn:"Lưu ý: Bạn phải vô hiệu hóa NAT của kết nối WAN, nếu không cấu hình DHCP Relay sẽ có thể không có hiệu lực!"
	},
	dhcpClient:{
		et:"Danh sách khách hàng DHCP",
		t_info:"Trang này hiển thị thông tin của tất cả các khách hàng DHCP trên mạng.",
		t_name:"Tên khách hàng",
		t_ip:"IP được gán",
		t_time:"Thời gian đăng kí"
	},
	dhcpStatic:{
		et:"Địa chỉ dự trữ DHCP",
		t_info:"Trang này hiển thị địa chỉ IP tĩnh được gán bởi máy chủ DHCP và cho phép bạn điều chỉnh các cấu hình này bằng cách bấm vào các ô tương ứng.",
		t_group:"Nhóm"
	},
	dhcpStaticEdit:{
		et:"Địa chỉ dự trữ DHCP",
		t_info:"Các địa chỉ IP tĩnh của máy chủ DHCP có thể được cấu hình trên trang này."
	},
	dhcpCond:{
		et:"Vùng dự trữ có điều kiện DHCP",
		t_info: "Trang này hiển thị cài đặt lớp nhà cung cấp và cho phép bạn thiết lập các thông số cho lớp nhà cung cấp của bạn bằng cách bấm vào các ô tương ứng.",
		t_vendor:"ID nhà cung cấp",
		t_poolstart:"Địa chỉ IP bắt đầu  ",
		t_poolend:"Kết thúc địa chỉ IP",
		t_facility:"Cơ sở"
	},
	dhcpCondEdit:{
		et:"Vùng dự trữ có điều kiện DHCP",
		t_info:"Các dãy IP lớp nhà cung cấp có thể được thiết lập trên trang này.",
		t_facility:"cơ sở:",
		t_vendor:"ID nhà cung cấp:",
		t_poolstart:"Địa chỉ IP bắt đầu:",
		t_poolend:"Kết thúc địa chỉ IP:",
		t_devtype:"Loại thiết bị:",
		t_camera:"Máy ảnh",
		t_phone:"Điện thoại  ",
		t_addopt1:"Thêm lựa chọn:",
		t_optval1:"Giá trị lựa chọn",
		t_addopt2:"Thêm lựa chọn:",
		t_optval2:"Giá trị lựa chọn",
		t_opt240:s_str.option+" 240",
		t_opt241:s_str.option+" 241",
		t_opt242:s_str.option+" 242",
		t_opt243:s_str.option+" 243",
		t_opt244:s_str.option+" 244",
		t_opt245:s_str.option+" 245"
	},
	wlFrequency: {
		et: "Lựa chọn băng tần kép",
		t_tip: "Vui lòng chọn hoặc xóa hộp chọn để kích hoạt hoặc vô hiệu hóa tần số vô tuyến được đề xuất."
	},
	wlBasic:
	{
		et:"Cài đặt mạng không dây",
		t_info:"Thông số cơ bản của mạng không dây có thể được cấu hình trên trang này.",
		t_enmssid:"Kích hoạt Multi SSID",
		t_warn1:"Vui lòng đảm bảo bạn đã chọn đúng quốc gia để tuân thủ luật pháp địa phương.",
		t_warn2:"Cài đặt không chính xác có thể gây ra nhiễu.",
		t_enwl:"Kích hoạt tính năng Router phát vô tuyến không dây",
		t_enbcast:"Kích hoạt tính năng phát thanh SSID ",
		t_enwds:"Bật WDS",
		t_brssid:"SSID (được bắc cầu):",
		t_brbssid:"Địa chỉ MAC (bắt cầu):",
		t_eg:"e.g. 00:1D:0F:11:22:33",
		t_scan:"Quét",
		t_wepidx:"Mục lục WEP:",
		ssidName: "Tên mạng không dây",
		t_ssid: "(Còn được gọi là SSID)"
	},
	wlBasic5G:
	{
		et:"Cài đặt mạng không dây (5GHz)",
		t_info:"Thông số cơ bản của mạng không dây có thể được cấu hình trên trang này.",
		t_enmssid:"Kích hoạt Multi SSID",
		t_warn1:"Vui lòng đảm bảo bạn đã chọn đúng quốc gia để tuân thủ luật pháp địa phương.",
		t_warn2:"Cài đặt không chính xác có thể gây ra nhiễu.",
		t_enwl:"Kích hoạt tính năng Router phát vô tuyến không dây",
		t_enbcast:"Kích hoạt tính năng phát thanh SSID ",
		t_enwds:"Bật WDS",
		t_brssid:"SSID (được bắc cầu):",
		t_brbssid:"Địa chỉ MAC (bắt cầu):",
		t_eg:"e.g. 00:1D:0F:11:22:33",
		t_scan:"Quét",
		t_wepidx:"Mục lục WEP:",
		ssidName: "Tên mạng không dây",
		t_ssid: "(Còn được gọi là SSID)"
	},
	wlScan:{
		et:"Danh sách AP",
		t_info:"Các AP được quét trong khu vực:",
		t_aps:"APs:",
		t_signal:"Tín hiệu mạnh"
	},
	wlScan5G:{
		et:"Danh sách AP",
		t_info:"Các AP được quét trong khu vực:",
		t_aps:"APs:",
		t_signal:"Tín hiệu mạnh"
	},
    wlQss:{
		et:"WPS (Cài đặt bảo vệ Wi-Fi)",
		t_note:"Lưu ý: TTính năng WPS không hỗ trợ bảo mật WEP, xác thực WPA/WPA2-Doanh nghiệp hoặc mã hóa TKIP.",
		t_wlqss_t2:"Vô tuyến không dây của router đã bị vô hiệu hóa, Bấm",
		t_wlqss_t3:"Ở đây",
		t_wlqss_t4:"Kích hoạt ",
		ssid_wps_1:"Quảng bá SSID không dây đã bị vô hiệu hóa, Bấm chọn",
		ssid_wps_2:"Ở đây",
		ssid_wps_3:"Kích hoạt ",
		t_curpin:"PIN hiện tại:",
		restore:"Khôi phục PIN",
		genNew:"Tạo PIN mới",
		t_addnewdev:"Thêm vào thiết bị mới:",
		addNew:"Thêm thiết bị",
		t_pinDisabled:"vô hiệu hóa PIN thiết bị"
	},
    wlQss5G:{
		et:"WPS (Cài đặt bảo vệ Wi-Fi)",
		t_note:"Lưu ý: TTính năng WPS không hỗ trợ bảo mật WEP, xác thực WPA/WPA2-Doanh nghiệp hoặc mã hóa TKIP.",
		t_wlqss_t2:"Vô tuyến không dây của router đã bị vô hiệu hóa, Bấm",
		t_wlqss_t3:"Ở đây",
		t_wlqss_t4:"Kích hoạt ",
		ssid_wps_1:"Quảng bá SSID không dây đã bị vô hiệu hóa, Bấm chọn",
		ssid_wps_2:"Ở đây",
		ssid_wps_3:"Kích hoạt ",
		t_curpin:"PIN hiện tại:",
		restore:"Khôi phục PIN",
		genNew:"Tạo PIN mới",
		t_addnewdev:"Thêm vào thiết bị mới:",
		addNew:"Thêm thiết bị",
		t_pinDisabled:"vô hiệu hóa PIN thiết bị"
	},
	wlQssAdv:{
		et:"Cài đặt WPS", 
		t_enpin:"Nhập mã PIN thiết bị mới.",
		t_press:"Nhấn nút WPS của thiết bị mới trong vòng 2 phút."
	},
	wlQssAdv5G:{
		et:"Cài đặt WPS", 
		t_enpin:"Nhập mã PIN thiết bị mới.",
		t_press:"Nhấn nút WPS của thiết bị mới trong vòng 2 phút."
	},
	wlSec:{
		et:"Cài đặt bảo mật mạng không dây",		
		t_note1:"Lưu ý: Bảo mật WEp và mã hóa TKIP không được hỗ trợ ở chế độ chỉ 11n.",
		t_note2:"Lưu ý: Bảo mật WEP, xác thực WPA/WPA2-Doanh nghiệp và mã hóa TKIP không được hỗ trợ khi WPS được kích hoạt.",
		t_note3:"Lưu ý: Mã WEP không được hỗ trợ khi Mạng khách được kích hoạt.",
		t_note4:"Đối với an ninh mạng, nó được khuyến khích mạnh mẽ để cho phép bảo mật không dây và chọn mã hóa WPA2-PSK AES.",
		t_weptype:"Định dạng WEP Key:",
		t_hex:"thập lục phân",
		t_selkey:"Chọn chính:",
		t_wepkey:"WEP Key",
		t_time:"Chu kỳ cập nhật nhóm chính:",
		t_timeval:"giá trị nhỏ nhất là 30, 0 nghĩa là không cập nhật",
		t_srvIp:"IP máy chủ RADIUS:",
		t_srvPort:"Cổng máy chủ RADIUS:",
		t_srvPwd:"Mật mã máy chủ RADIUS:",
		t_wlRadiusPort: "(1-65535, 0 thay cho cổng mặc định 1812)",
		t_wlSec_t19: "Chu kỳ cập nhật nhóm chính",
		t_wpaPersonal: "WPA/WPA2 - Người dùng cá nhân",
		t_wpaEnterprise: "WPA/WPA2 - Doanh nghiệp"
	},
	wlSec5G:{
		et:"Cài đặt bảo mật mạng không dây",		
		t_note1:"Lưu ý: Bảo mật WEp và mã hóa TKIP không được hỗ trợ ở chế độ chỉ 11n.",
		t_note2:"Lưu ý: Bảo mật WEP, xác thực WPA/WPA2-Doanh nghiệp và mã hóa TKIP không được hỗ trợ khi WPS được kích hoạt.",
		t_note3:"Lưu ý: Mã WEP không được hỗ trợ khi Mạng khách được kích hoạt.",
		t_note4:"Đối với an ninh mạng, nó được khuyến khích mạnh mẽ để cho phép bảo mật không dây và chọn mã hóa WPA2-PSK AES.",
		t_weptype:"Định dạng WEP Key:",
		t_hex:"thập lục phân",
		t_selkey:"Chọn chính:",
		t_wepkey:"WEP Key",
		t_time:"Chu kỳ cập nhật nhóm chính:",
		t_timeval:"giá trị nhỏ nhất là 30, 0 nghĩa là không cập nhật",
		t_srvIp:"IP máy chủ RADIUS:",
		t_srvPort:"Cổng máy chủ RADIUS:",
		t_srvPwd:"Mật mã máy chủ RADIUS:",
		t_wlRadiusPort: "(1-65535, 0 thay cho cổng mặc định 1812)",
		t_wlSec_t19: "Chu kỳ cập nhật nhóm chính",
		t_wpaPersonal: "WPA/WPA2 - Người dùng cá nhân",
		t_wpaEnterprise: "WPA/WPA2 - Doanh nghiệp"
	},
	wlAcl:
	{
		et:"Bộ lọc MAC mạng không dây",
		t_info:"Bạn có thể cấu hình bộ lọc MAC mạng không dây để cho phép bạn kiểm soát truy cập mạng không dây trên mạng ở trang này.",
		t_acl:"Bộ lọc MAC mạng không dây",
		t_rule:"Quy tắc lọc",
		t_deny:"Từ chối",
		t_item1:"Các trạm theo quy định của bất kỳ mục cho phép trong danh sách truy cập.",
		t_allow:"Cho phép",
		t_item2:"Các trạm theo quy định của bất kỳ mục cho phép trong danh sách truy cập."
	},
	wlAcl5G:
	{
		et:"Bộ lọc MAC mạng không dây",
		t_info:"Bạn có thể cấu hình bộ lọc MAC mạng không dây để cho phép bạn kiểm soát truy cập mạng không dây trên mạng ở trang này.",
		t_acl:"Bộ lọc MAC mạng không dây",
		t_rule:"Quy tắc lọc",
		t_deny:"Từ chối",
		t_item1:"Các trạm theo quy định của bất kỳ mục cho phép trong danh sách truy cập.",
		t_allow:"Cho phép",
		t_item2:"Các trạm theo quy định của bất kỳ mục cho phép trong danh sách truy cập."
	},
	wlAclAdv:
	{
		et:"Thêm hoặc chỉnh sửa lọc đầu vào địa chỉ MAC không dây. ",
		t_info:"Bạn có thể cấu hình bộ lọc MAC mạng không dây để cho phép bạn kiểm soát truy cập mạng không dây trên mạng ở trang này.",
		t_acleg:"e.g. 00:1D:0F:11:22:33",
		t_host:"Mạng chủ:"
	},
	wlAclAdv5G:
	{
		et:"Thêm hoặc chỉnh sửa lọc đầu vào địa chỉ MAC không dây. ",
		t_info:"Bạn có thể cấu hình bộ lọc MAC mạng không dây để cho phép bạn kiểm soát truy cập mạng không dây trên mạng ở trang này.",
		t_acleg:"e.g. 00:1D:0F:11:22:33",
		t_host:"Mạng chủ:"
	},
	wlAdv:
	{
		et:"Nâng cao mạng không dây",
		t_txpow:"Truyền điện:",
		t_beacon:"Mốc báo khoảng cách:",
		t_rts:"Mức RTS:",
		t_frag:"Mức độ phân mảnh:",
		t_dtim:"Khoảng DTIM:",
		t_ensgi:"Kích hoạt tính năng GI ngắn",
		t_eniso:"Kích hoạt cách ly khách hàng",
		t_enwmm:"Bật WMM",
		t_notice:"Chú ý: Để có hiệu suất tốt hơn, Ngưỡng phân mảnh sẽ bị vô hiệu hóa khi chế độ không dây bao gồm 11n và 11ac."
	},
	wlAdv5G:
	{
		et:"Nâng cao mạng không dây",
		t_txpow:"Truyền điện:",
		t_beacon:"Mốc báo khoảng cách:",
		t_rts:"Mức RTS:",
		t_frag:"Mức độ phân mảnh:",
		t_dtim:"Khoảng DTIM:",
		t_ensgi:"Kích hoạt tính năng GI ngắn",
		t_eniso:"Kích hoạt cách ly khách hàng",
		t_enwmm:"Bật WMM",
		t_notice:"Chú ý: Để có hiệu suất tốt hơn, Ngưỡng phân mảnh sẽ bị vô hiệu hóa khi chế độ không dây bao gồm 11n và 11ac."
	},
	wlStats:{
		et:"Trạng thái thống kê mạng không dây",
		t_info:"Trang này hiển thị các thông tin cơ bản của tất cả các trạm kết nối với mạng không dây.",
		t_tip:"Trạm mạng không dây kết nối hiện tại:",
		t_curstat1:"Trạng thái hiện tại",
		t_curstat2:"Trạng thái hiện tại",
		t_rxpkts1:"Các gói tin đã nhận",
		t_rxpkts2:"Các gói tin đã nhận",
		t_txpkts1:"Các gói tin gửi",
		t_txpkts2:"Các gói tin gửi"
	},
	wlStats5G:{
		et:"Trạng thái thống kê mạng không dây",
		t_info:"Trang này hiển thị các thông tin cơ bản của tất cả các trạm kết nối với mạng không dây.",
		t_tip:"Trạm mạng không dây kết nối hiện tại:",
		t_curstat1:"Trạng thái hiện tại",
		t_curstat2:"Trạng thái hiện tại",
		t_rxpkts1:"Các gói tin đã nhận",
		t_rxpkts2:"Các gói tin đã nhận",
		t_txpkts1:"Các gói tin gửi",
		t_txpkts2:"Các gói tin gửi"
	},
	wlGuest:
	{
		et:"Mạng khách",
		gn:"Mạng khách",
		t_wlGuest_t1:"Tính năng mạng không dây đã vô hiệu hóa, bấm",
		t_wlGuest_t2_1:"Ở đây",
		t_wlGuest_t3_1:"Kích hoạt ",
		t_wlGuest_t2_2:"Ở đây",
		t_wlGuest_t3_2:"Kích hoạt ",
		t_gnInfo:"Bạn có thể cấu hình một mạng mạng không dây cho khách.",
		t_gNet:"Mạng khách:",
		t_ssid:"Tên mạng:",
		t_sec:"Bảo mật:",
		t_lAccess:"Cho phép khách hàng truy cập vào mạng nội bộ của tôi:",
		t_uAccess:"Cho phép khách hàng truy cập vào chia sẻ lưu trữ USB của tôi:",
		t_wIso:"Cách ly mạng khách",
		t_gNtc:"Kiểm soát băng thông mạng khách: ",
		t_gnTc_warn:"Chức năng kiểm soát băng thông của thiết bị đã vô hiệu hóa, Bấm",
		t_minrate:"Băng thông tối thiểu",
		t_maxrate:"Băng thông tối đa",
		t_up:"Băng thông ngõ ra:",
		t_down:"Băng thông vào:",
		t_accTime:"Thời gian truy cập:",
		t_bandSel: "Chọn băng thông",
		t_stanum: "Số máy khách tối đa",
		t_disWlSec: "vô hiệu hóa bảo mật không dây",
		t_time:"Chu kỳ cập nhật nhóm chính",
		t_timeval:"giá trị nhỏ nhất là 30, 0 nghĩa là không cập nhật",
		t_timeout: "Thời gian nghỉ  ",
		t_schedule: "Thời gian biểu",
		t_wlSecduleTip: "Bấm chọn bảng thời gian biểu hoặc sử dụng nút 'Thêm' để chọn khoảng thời gian bạn muốn mạng khách tự động tắt!",
		t_wlSched: "Thời gian biểu mạng không dây",
		t_setto: "Ứng dụng đến",
		t_start: "Thời gian bắt đầu",
		t_end: "Thời gian kết thúc",
		t_day: "Mỗi ngày",
		t_week: "Mỗi tuần",
		t_clear: "Xóa thời gian biểu",
		t_uptime1: "Thời gian còn lại"
	},
	wlGuestStatus:
	{
		et:"Trạng thái mạng khách",
		t_info:"Trang này hiển thị các thông tin cơ bản của tất cả các khách kết nối vào mạng không dây này.",
		t_tip:"Khách hàng kết nối với mạng khách hiện tại:",
		t_curstat1:"Trạng thái hiện tại",
		t_curstat2:"Trạng thái hiện tại",
		t_rxpkts1:"Các gói tin đã nhận",
		t_rxpkts2:"Các gói tin đã nhận",
		t_txpkts1:"Các gói tin gửi",
		t_txpkts2:"Các gói tin gửi"
	},
	usbManage:{
		et:"Lưu trữ USB Mass ",
		t_info:"Trang này cung cấp các thông tin cơ bản về các thiết bị lưu trữ USB mass, để cấu hình chia sẻ lưu trữ/ FTP/ Máy chủ Media, xin vui lòng nhấp vào danh mục tương ứng bên trái.",
		t_usb_con:"Danh sách lưu trữ Mass USB:",
		t_usb_discon:"Lưu trữ USB Mass ngắt kết nối!",
		t_step1:"Bấm Refresh để dò các thiết bị USB. Router sẽ tự động kích hoạt hai thiết bị lưu trữ USB được kết nối đầu tiên hoặc lên đến tám nhãn trong tổng số.",
		t_step2:"Nếu bạn muốn sử dụng nhãn khác trong thiết bị lưu trữ của bạn, vui lòng \"Vô hiệu hóa\" nhãn không sử dụng và \"Kích hoạt\"nhãn mong muốn khác.",
		t_step3:"Vui lòng bấm chọn \"Ngắt kết nối\" trước khi tháo thiết bị USB để tránh mất mát dữ liệu hoặc gây hư hỏng cho thiết bị.",
		t_dev:"USB Mass dự trữ được hỗ trợ:",
		t_devlist:"đĩa cứng, ổ đĩa flash hoặc đầu đọc thẻ nhớ",
		t_fs:"Loại hệ thống tập tin được hỗ trợ:",
		t_fslist:"FAT32 và NTFS",
		t_vol:"Volumes được hỗ trợ:",
		t_volcnt:"Chỉ hai thiết bị lưu trữ USB với 8 nhãn có thể được kích hoạt cùng lúc. Lên đến 4 thiết bị lưu trữ USB với 8 nhãn có thể được nhận dạng."
	},
	usbUserAccount:{
		et:"Tài khoản người dùng",
		t_info:"Trang này cho phép bạn cấu hình các tài khoản người dùng cho chia sẻ lưu trữ/ máy chủ FTP. Vui lòng bấm vào cài đặt để đảm bảo cấu hình của bạn hoạt động.",
		t_note:"Super User có toàn quyền truy cập cho tất cả các hoạt động và các thư mục chia sẻ.",
		t_chidx:"Chọn mục lục:",
		t_newusr:"Tên đăng nhập mới:",
		t_newpwd:"Mật mã mới:",
		t_apply:"(Sẽ không có hiệu lực cho đến khi bạn áp dụng những thay đổi)"
	},
	usbSmbSrv:{
		et:"Cài đặt chia sẻ dự trữ",
		t_info:"Chia sẻ lưu trữ cho phép bạn chia sẻ các tập tin được lưu trên một thiết bị lưu trữ USB với máy tính khác trên mạng nội bộ.",
		t_stat:"Trạng thái máy chủ",
		t_anony:"Truy cập nặc danh đến tất cả các nhãn.",
		t_fldtbl:"Bảng thư mục:",
		t_apply:"(Bất kỳ sửa đổi nào trong bảng này sẽ không có hiệu lực cho đến khi bạn áp dụng những thay đổi này.)",
		t_shname:"Tên chia sẻ",
		t_dir:"Danh mục",
		t_access:"Truy cập người dùng",
		t_facc:"Truy cập đầy đủ",
		t_ronly:"Chỉ đọc",
		t_nacc:"Không truy cập",
		t_note1:"\"Super User\" có toàn quyền truy cập (Read & Write) cho tất cả các thư mục chia sẻ",
		t_newfld:"Thêm thư mục mới",
		t_note2:"Tính năng chia sẻ lưu trữ  dựa trên các giao thưc NetBIOS / SMB được hỗ trợ bởi hệ điều hành Windows và một số hệ điều hành khác.",
		t_note3:"Nặc danh: tất cả các hoạt động nặc danh sẽ được chia sẻ mà không cần yêu cầu xác thực.",
		t_note4:"Bạn sẽ có quyền truy cập các thư mục chia sẻ bởi các phương pháp sau đây:",
		t_forwin:"Đối với hệ điều hành Windows:",
		t_forwin2:"Mở cửa sổ \"Run\" trong trình đơn Start và nhập \\(Địa chỉ IP) hoặc \\(Địa chỉ IP)\(Tên chia sẻ)",
		t_formac:"Đối với hệ điều hành Mac OS:",
		t_formac2:"Mở cửa sổ \"Kết nối đến máy chủ\" trong trình đơn Đi và  nhập://(Địa chỉ IP) hoặc smb://(Địa chỉ IP)/(Tên chia sẻ)."
	},
	usbFolderBrowse:{
		et:"Duyệt thu mục",
		t_info1:"Trang này cho phép thiết lập các thư mục được chia sẻ cùng với truy cập uỷ quyền cho các dịch vụ chia sẻ lưu trữ. Các cấu hình này sẽ không hoạt động khi truy cập nặc danh đã kích hoạt.",
		t_info2:"Trang này cho phép bạn thiết lập các thư mục chia sẻ cùng với truy cập uỷ quyền cho các dịch vụ FTP.",
		t_info3:"Trang này cho phép bạn thiết lập một thư mục quét cho dịch vụ media DLNA.",
		t_shname:"Tên chia sẻ:",
		t_dir:"Danh mục",
		t_browse:"Duyệt",
		t_hide:"Ấn đi",
		t_tbl:"Bảng điều khiển truy cập người dùng:",
		t_vol:"Chọn nhãn:",
		t_selvol:"Vui lòng chọn âm lượng",
		t_author:"Ủy quyền truy cập",
		t_note:"Super User có toàn quyền truy cập cho tất cả các hoạt động và các thư mục chia sẻ."
	},
	ftpSrv:{
		et:"Cài đặt máy chủ FTP ",
		t_info:"Một máy chủ File Transfer Protocol (FTP) cho phép bạn chia sẻ các tập tin trong thiết bị lưu trữ USB qua mạng nội bộ hoặc mạng công cộng. Các thư mục chia sẻ phải được thiết lập bao gồm cả quyền sử dụng đối với từng thư mục.",
		t_stat:"Trạng thái máy chủ:",
		t_acc:"Truy cập Internet:",
		t_iaddr:"Địa chỉ Internet:",
		alg_notice:"(FTP ALG phải được kích hoạt trước các cấu hình này sẽ hoạt động.)",
		t_port:"Cổng dịch vụ:",
		t_defport:"(Mặc định là 21, không thay đổi trừ khi cần thiết)",
		t_ftbl:"Bảng thư mục:",
		t_apply:"(Bất kỳ sửa đổi nào trong bảng này sẽ không có hiệu lực cho đến khi bạn áp dụng những thay đổi này.)",
		t_shname:"Tên chia sẻ",
		t_dir:"Danh mục",
		t_usridx:"Mục lục người dùng",
		t_note1:"Super User có toàn quyền truy cập cho tất cả các hoạt động và các thư mục chia sẻ.",
		t_newfld:"Thêm thư mục mới",
		t_note2:"Bạn có thể truy cập vào các thư mục chia sẻ bằng cách nhập các miền sau đây trong Windows Explorer hoặc phần mềm FTP khác:",
		t_note3:"Các máy chủ FTP sẽ được khởi động lại gây kết thúc tất cả các kết nối FTP hiện tại khi bạn bấm Áp dụng."
	},
	dlnaManage:{
		et:"Cài đặt Máy chủ đa phương tiện",
		t_enable:"Cho phép máy chủ",
		t_name:"Tên máy chủ:",
		t_scan:"Nội dung quét:",
		t_manual:"Quét bằng tay",
		manualScan:"Quét ngay",
		t_auto:"Tự động quét:",
		t_every:"Tất cả",
		t_hour:"hàng giờ",
		t_tip:"Bạn đã chia sẻ các nội dung sau:",
		t_id: "ID",
		t_shname:"Tên chia sẻ",
		t_fldname:"Tên thu mục",
		addContent:"Thêm thư mục mới"
	},
	printSrv:{
		et:"Cài đặt máy chủ in",
		t_stat:"Trạng thái máy chủ:",
		online:"Trực tuyến",
		offline:"Ngoại tuyến",
		print_en:"Bắt đầu",
		print_dis:"Dừng"
	},
	basicSec: {
		et: "Bảo mật cơ bản",
		t_stat: "Tường lửa",
		t_pptp: "PPTP Pass-through",
		t_l2tp: "L2TP Pass-through",
		t_ipsec: "IPSec Pass-through"
	},
	defGateway:{
		et:"Cài đặt cổng mặc định",
		t_info1:"Lưu ý1:Chọn giao diện WAN ưu tiên làm gateway mặc định của hệ thống.",
		t_info2:"Lưu ý 2: Giao diện WAN này đã được chọn cho một nhóm khác và không thể được chọn làm gateway mặc định của hệ thống.",
		t_selwan:"Chọn giao diện WAN:"
	},
	route:{
		et:"Tuyến tĩnh",
		t_info:"Trang này hiển thị bảng router tĩnh. Bấm vào Thêm mới để nhập một Router tĩnh hoặc bấm chỉnh sửa để chỉnh sửa một mục hiện tại.",
		t_dstip:"Địa chỉ IP đích"
	},
	routeEdit:{
		et:"Tuyến tĩnh",
		t_info:"Thông số tuyến tĩnh có thể được cấu hình trên trang này.",
		t_dstip:"Địa chỉ IP đích:"
	},
	rip:{
		et:"Cài đặt RIP",
		t_info:"Để kích hoạt RIP cho giao diện WAN, chọn phiên bản mong muốn và hoạt động của RIP cũng như kiểm tra 'Kích hoạt'. Để vô hiệu hóa RIP trên giao diện WAN, bỏ chọn 'Kích hoạt' và bấm vào 'Lưu' để cho phép cấu hình để hoạt động.",
		t_note:"Lưu ý: Không thể cấu hình RIP trên giao diện WAN khi kích hoạt NAT.",
		t_ver:"Phiên bản"
	},
	defGateway6:{
		et:"Cài đặt GatewayIPv6 mặc định",
		t_info:"Chọn giao diện WAN ưu tiên làm gateway IPv6 hệ thống mặc định.",
		t_selwan:"Chọn giao diện WAN  "
	},
	route6:
	{
		et:"Định tuyến tĩnh IPv6",
		t_info:"Trang này hiển thị bảng route IPv6 tĩnh định. Bấm vào Thêm mới để nhập một route tĩnh hoặc bấm chỉnh sửa để chỉnh sửa một mục hiện tại.",
		t_dstip6:"Địa chỉ IPv6 đích/chiều dài Prefix"
	},
	route6Edit:
	{
		et:"Định tuyến tĩnh IPv6",
		t_info:"Tham số định tuyến tĩnh IPv6 có thể được cấu hình tại trang này.",
		t_note:"Lưu ý: Thiết bị này chỉ hỗ trợ địa chỉ IPv6 chứa độ dài tiền tố 8/16/24/32/40/48/56/64.",
		t_dstip6:"Địa chỉ IPv6 đích",
		t_plen:"Chiều dài tiền tố"
	},
	virtualServer:
	{
		et:"Máy chủ ảo  ",
		t_info:"Một máy chủ ảo xác định ánh xạ từ các cổng dịch vụ WAN tới máy chủ mạng LAN. Tất cả các yêu cầu từ Internet đến các cổng dịch vụ được chỉ định sẽ được chuyển hướng đến các thiết bị xác định bởi địa chỉ IP máy chủ.",
		t_port:"Cổng dịch vụ",
                t_interPort:"Cổng nội bộ"
	},
	vtlServEdit:
	{
		et:"Máy chủ ảo  ",
		t_info:"Một máy chủ ảo xác định ánh xạ từ các cổng dịch vụ WAN tới máy chủ mạng LAN. Tất cả các yêu cầu từ Internet đến các cổng dịch vụ được chỉ định sẽ được chuyển hướng đến các thiết bị xác định bởi địa chỉ IP máy chủ.",
		t_note1:"Lưu ý: Cấu hình máy chủ ảo chỉ được hỗ trợ khi có giao diện khả dụng.",
		t_note2:"Cổng dịch vụ được gán cho Quản lý từ xa hoặc CWMP không thể sử dụng.",
		t_note3:"Các cổng dịch vụ thiết cho quản lý từ xa không thể sử dụng được.",
		t_port:"Cổng dịch vụ:",
		t_cport:"Cổng dịch vụ chung:",
		t_sel:"---Vui lòng chọn---",
                t_interPort:"Cổng nội bộ:",
		t_note4:"(XX hoặc để trống. Nếu để trống, cổng nội bộ bằng với cổng dịch vụ)"
	},
	portTrigger:
	{
		et:"Cổng kích hoạt  ",
		t_info:"Các ứng dụng khác nhau đòi hỏi nhiều kết nối, ví dụ như trò chơi trực tuyến, hội nghị truyền hình, VoIP, vv... Do các bức tường lửa nội bộ, các ứng dụng này sẽ không hoạt động hiệu quả với một router NAT thuần túy. Trong những trường hợp này, cổng kích hoạt có thể cung cấp một giải pháp trong việc cải thiện hiệu suất của các ứng dụng cụ thể.",
		t_tport:"Cổng kích hoạt",
		t_proto:"Giao thức kích hoạt",
		t_oport:"Cổng mở",
		t_oproto:"Giao thức mở"
	},
	portTrigEdit:
	{
		et:"Cổng kích hoạt  ",
		t_info:"Các ứng dụng khác nhau đòi hỏi nhiều kết nối, ví dụ như trò chơi trực tuyến, hội nghị truyền hình, VoIP, vv... Do các bức tường lửa nội bộ, các ứng dụng này sẽ không hoạt động hiệu quả với một router NAT thuần túy. Trong những trường hợp này, cổng kích hoạt có thể cung cấp một giải pháp trong việc cải thiện hiệu suất của các ứng dụng cụ thể.",
		t_note:"Lưu ý: Cổng kích hoạt chỉ được hỗ trợ khi có giao diện khả dụng.",
		t_tport:"Cổng kích hoạt:",
		t_tproto:"Giao thức kích hoạt:",
		t_oport:"Cổng mở:",
		t_oproto:"Giao thức mở:",
		t_cport:"Cổng dịch vụ chung:",
		t_sel:"---Vui lòng chọn---"
	},
	dmz:
	{
		t_info:"Tính năng máy chủ DMZ mở tất cả các cổng dịch vụ cho một máy chủ nội bộ để giao tiếp hai chiều.",
		t_status:"Trạng thái DMZ:",
		t_hostip:"Địa chỉ IP máy chủ DMZ:"
	},
	upnp:
	{
		t_info:"Trang này hiển thị tình trạng và các cài đặt UPnP.",
		t_status:"Trạng thái UPnP hiện tại:",
		t_list:"Danh sách các thiết lập UPnP hiện tại",
		t_desc:"Mô tả App",
		t_export:"Cổng bên ngoài",
		t_inport:"Cổng nội bộ"
	},
	parentCtrl:{
		et:"Quyền kiểm soát của phụ huynh  ",
		t_info:"Quyền kiểm soát của phụ huynh có thể được sử dụng để quản lý tất cả các hoạt động Internet bao gồm giới hạn sử dụng và/hoặc truy cập đến trang web xác định đối với tất cả các máy khách trong mạng trong một khoảng thời gian xác định.",
		t_en:"Kích hoạt tính năng quyền kiểm soát cha mẹ",
		t_pmac:"Địa chỉ MAC của máy cha mẹ:",
		t_curmac:"Địa chỉ MAC của PC hiện tại:",
		t_copy1:"Sao chép vào ở trên",
		t_lanmac:"Địa chỉ MAC trong mạng LAN hiện tại:",
		t_copy2:"Sao chép vào",
		t_sel:"--Vui lòng chọn--",
		t_mac1:s_str.macaddr+"-1",
		t_mac2:s_str.macaddr+"-2",
		t_mac3:s_str.macaddr+"-3",
		t_mac4:s_str.macaddr+"-4",
		t_setto:"Ứng dụng đến:",
		t_start:"Thời gian bắt đầu",
		t_end:"Thời gian kết thúc",
		t_day:"Mỗi ngày",
		t_week:"Mỗi tuần",
		t_clear:"Xóa thời gian biểu",
		t_url:"Thêm URL:",
		t_detail:"Chi tiết",
		t_apply:"(Sẽ không có hiệu lực cho đến khi bạn lưu những thay đổi này)"
	},
	fwRules:{
		et:"Quản lý quy đinh kiểm soát truy cập",
	    t_info:"Thiết bị này có thể hạn chế các hoạt động Internet cho các máy chủ mạng LAN quy định. Bạn có thể thiết lập và kết hợp các quy tắc kiểm soát truy cập để quản lý có hiệu quả mạng của bạn.",
		t_en:"Kích hoạt tính năng kiểm soát truy cập Internet",
		t_defrule:"Quy tắc lọc mặc định",
		t_allow:"Cho phép",
		t_rule1:"Các gói dữ liệu không được xác định bởi bất kỳ quy tắc lọc nào để vượt qua thiết bị này.",
		t_deny:"Từ chối",
		t_rule2:"Các gói dữ liệu không được xác định bởi bất kỳ quy tắc lọc nào để vượt qua thiết bị này.",
		t_note:"Lưu ý: Thiết bị sẽ kết hợp gói tin đến với từng điều luật lọc một trong danh sách và áp dụng điều luật phù hợp đầu tiên. Nếu gói tin không được xác định bởi bất cứ điều luật lọc nào trong danh sách, thì Điều luật lọc mặc định sẽ có hiệu lực.",
        t_host:"Máy chủ LAN",
		t_target:"Mục tiêu",
		t_sche:"Thời gian biểu",
		t_rule:"Quy tắc  ",
		edit:"Chỉnh sửa"
	},
	fwRulesEdit:{
		et:"Thêm mục kiểm soát truy cập Internet.",
		t_info:"Một quy tắc kiểm soát truy cập Internet có thể được cấu hình trên trang này.",
		t_lan:"Máy chủ LAN:",
		t_addlan:"Thêm máy chủ LAN.",
		t_wan:"Mục tiêu:",
		t_addwan:"Thêm mục tiêu",
		t_sche:"Thời gian biểu:",
		t_addsche:"Thêm Thời gian biểu",
		t_action:"Quy tắc:",
		t_direction:"Hướng:",
		t_in:"Trong",
		t_out:"RA",
		t_protocol:"Giao thức:"
	},
	fwLan:{
		et:"Host Settings",
		t_addr:"Địa chỉ thông tin"
	},
	fwLanEdit:{
		et:"Thêm hoặc chỉnh sửa một đầu vào máy chủ"
	},
	fwWan:{
		et:"Cài đặt mục tiêu",
		t_detail:"Chi tiết"
	},
	fwWanEdit:{
		et:"Thêm hoặc Chỉnh sửa đầu vào mục tiêu",
		urlMode:"Địa chỉ URL",
		t_addurl:"Thêm địa chỉ URL:",
		t_detail:"Chi tiết",
		t_apply:"(Sẽ không có hiệu lực cho đến khi bạn lưu những thay đổi này)"
	},
	fwSche:{
		et:"Cài đặt thời gian biểu"
	},
	fwScheEdit:{
		et:"Thêm hoặc Chỉnh sửa một đầu vào thời gian biểu",
		t_info:"Thời gian biểu có thể được cài đặt tại trang này.",
		t_setto:"Ứng dụng đến:",
		t_start:"Thời gian bắt đầu",
		t_end:"Thời gian kết thúc",
		t_day:"Mỗi ngày",
		t_week:"Mỗi tuần",
		t_clear:"Xóa thời gian biểu"
	},
	ddos:{
		et: "Bảo mật nâng cao",
		t_info:"Thông số DDoS có thể được thiết lập trên trang này.",
		t_dos:"Bảo vệ DoS:",
		t_note:"Lưu ý: Bảo vệ DoS sẽ không có hiệu lực cho đến khi Thống kê lưu lượng được kích hoạt.",
		t_icmp:"Kích hoạt tính năng lọc ICMP-Flood Attack",
		t_icmpth:"Mức gói ICMP-Flood ",
		t_udp:"Kích hoạt bộ lọc tấn công UDP-Flood ",
		t_udpth:"Mức các gói UDP- Flood",
		t_sync:"Kích hoạt tính năng  bộ lọc tấn công TCP-SYN-Flood ",
		t_syncth:"Mức gói TCP-SYN-Flood ",
		t_denywan: "Chặn gói ping từ cổng WAN",
		t_denylan: "Chặn gói ping từ cổng LAN",
		t_list:"Danh sách bị chặn máy chủ DOS"
	},
	ddos_host:{
		t_ip:"Host IP Address",
		t_mac:"Host MAC Address",
		t_clear:"Xóa tất cả"
	},
	local: {
		et: "Quản lý nội bộ",
		t_defrule: "Quy tắc quản lý",
		t_all: "Tất cả",
		t_cet: "Chỉ",
		t_rule1: "Các máy tính trên mạng LAN được phép truy cập tiện ích dựa trên Web của Router",
		t_rule2: "Các máy tính được liệt kê có thể duyệt các trang web được xây dựng để thực hiện nhiệm vụ quản trị",
		t_mac1: "MAC",
		t_curmac: "Địa chỉ MAC máy tính của bạn"
	},
	remote: {
		et: "Quản lý từ xa",
		t_port: "Cổng quản lý Web",
		t_host: "Địa chỉ IP quản lý từ xa",
		t_for_all: "(Nhập 255.255.255.255 cho tất cả)"
	},
	routeTbl: {
		et: "Bảng định tuyến hệ thống",
		t_id: "ID",
		t_dest: "Mạng đích",
		t_mask: "Subnet Mask",
		t_gw: "Cổng",
		t_intf: "Giao diện   "
	},
	fw6Rules:
	{
		et:"Điều luật tường lửa IPv6",
		t_info:"Thiết bị này có thể hạn chế hoạt động Internet cho máy chủ mạng LAN IPv6 quy định. Bạn có thể thiết lập và kết hợp các quy tắc kiểm soát truy cập để quản lý có hiệu quả mạng của bạn.",
		t_en:"Kích hoạt tường lửa IPv6",
		t_defrule:"Quy tắc lọc mặc định",
		t_allow:"Cho phép",
		t_rule1:"Các gói dữ liệu không được xác định bởi bất kỳ quy tắc lọc nào để vượt qua thiết bị này.",
		t_deny:"Từ chối",
		t_rule2:"Các gói dữ liệu không được xác định bởi bất kỳ quy tắc lọc nào để vượt qua thiết bị này.",
		t_note:"Lưu ý: Thiết bị sẽ kết hợp gói tin đến với từng điều luật lọc một trong danh sách và áp dụng điều luật phù hợp đầu tiên. Nếu gói tin không được xác định bởi bất cứ điều luật lọc nào trong danh sách, thì Điều luật lọc mặc định sẽ có hiệu lực..",
		t_host:"Máy chủ LAN IPv6",
		t_target:"Mục tiêu",
		t_sche:"Thời gian biểu",
		t_rule:"Quy tắc  "
	},
	fw6RulesEdit:
	{
		et:"Điều luật tường lửa IPv6",
		t_info:"Một quy tắc kiểm soát truy cập Internet IPv6 quy có thể được thiết lập trên trang này.",
		t_lan:"Máy chủ LAN IPv6",
		t_addlan:"Thêm máy chủ IPv6 LAN",
		t_wan:"Máy chủ WAN IPv6",
		t_addwan:"Thêm máy chủ IPv6 WAN",
		t_sche:"Thời gian biểu IPv6",
		t_addsche:"Thêm thời gian biểu IPv6",
		t_action:"Hoạt động",
		t_direction:"Hướng",
		t_in:"Trong",
		t_out:"RA"
	},
	fw6Lan:
	{
		et:"Máy chủ LAN IPv6",
		t_addr:"Thông tin địa chỉ IPv6"
	},
	fw6LanEdit:
	{
		et:"Máy chủ LAN IPv6"
	},
	fw6Wan:
	{
		et:"Máy chủ WAN IPv6",
		t_detail:"Chi tiết"
	},
	fw6WanEdit:
	{
		et:"Máy chủ WAN IPv6"
	},
	fw6Sche:
	{
		et:"Thời gian biểu tác vụ IPv6"
	},
	fw6ScheEdit:
	{
		et:"Thời gian biểu tác vụ IPv6",
		t_info:"Thời gian biểu có thể được cài đặt tại trang này.",
		t_setto:"Ứng dụng đến:",
		t_start:"Thời gian bắt đầu",
		t_end:"Thời gian kết thúc",
		t_day:"Mỗi ngày",
		t_week:"Mỗi tuần",
		t_clear:"Xóa thời gian biểu"
	},
	tunnel6:
	{
		et:"Đường hầm IPv6",
		t_note:"Lưu ý: Bạn phải cấu hình lại cài đặt tại trang này sau khi khởi động lại thiết bị. Bạn cũng phải đảm bảo kết nối WAN mong muốn được kết nối trước khi bạn cấu hình đường hầm.",
		t_mech:"Cơ chế",
		t_conftype:"Loại cấu hình",
		t_manual:"Hướng dẫn sử dụng",
		t_remote:"Địa chỉ IPv6 từ xa",
		t_masklen:"Độ dài mặt nạ IPv4",
		t_6rdpfx:"6RD Prefix",
		t_6rdplen:"Chiều dài 6RD Prefix",
		t_braddr:"Địa chỉ IPv4 Border Relay"
	},
	trafficCtrl:
	{
		et:"Điều khiển dải tần",
		t_info1:"Kiểm soát băng thông cho phép bạn kiểm soát băng thông của tất cả các thiết bị trên mạng LAN. Trang này cho phép thiết lập các thông số kiểm soát băng thông. Chỉ khi kích hoạt kiểm soát băng thông các quy định này sẽ hoạt động.",
		t_info2:"Kiểm soát băng thông cho phép bạn kiểm soát băng thông của tất cả các thiết bị trên mạng LAN. Trang này cho phép thiết lập các thông số Kiểm soát băng thông, đảm bảo băng thông IPTV và đảm bảo băng thông VoIP. Chỉ khi kích hoạt kiểm soát băng thông các quy tắc này sẽ hoạt động.",
		t_info3:"Kiểm soát băng thông cho phép bạn kiểm soát băng thông của tất cả các thiết bị trên mạng LAN. Trang này cho phép thiết lập các thông số kiểm soát băng thông và đảm bảo băng thông VoIP. Chỉ khi kích hoạt kiểm soát băng thông các quy tắc này sẽ có hoạt động.",
		t_info4:"Kiểm soát băng thông cho phép bạn kiểm soát băng thông của tất cả các thiết bị trên mạng LAN. Trang này cho phép thiết lập các thông số Kiểm soát băng thông, đảm bảo băng thông IPTV và đảm bảo băng thông VoIP. Chỉ khi kích hoạt kiểm soát băng thông các quy tắc này sẽ hoạt động.",
		t_note:"Lưu ý:Để tối ưu hóa kiểm soát băng thông, vui lòng cấu hình chính xác dạng đường truyền và băng thông.Nếu bạn không chắc chắn về thông tin này, vui lòng liên hệ ISP của bạn để được trợ giúp.",
		t_en:"Kích hoạt kiểm soát băng thông",
		t_type:"Dạng đường truyền:",
		t_other:"Khác",
		t_tup:"Băng thông ngõ ra:",
		t_tdown:"Băng thông vào:",
		t_info5:"Trang này cho phép bạn thiết lập các quy tắc kiểm soát lưu lượng. Các quy tắc kiểm soát lưu lượng sẽ chỉ có hiệu lực khi QoS được kích hoạt cùng với Thuật toán lập lịch biểu của luồng lên/ luồng xuống.",
		t_enVoip:"Bật tính năng bảo đảm băng thông VoIP ",
		t_graiptvon:"Kích hoạt tính năng bảo đảm băng thông IPTV",
		t_upgrabd:"Đảm bảo băng thông luồng lên:",
		t_downgrabd:"Đảm bảo băng thông luồng dữ liệu xuống:",
		t_rule:"Các quy tắc kiểm soát băng thông",
		t_guest_rule:"Quy định kiểm soát băng thông mạng khách",
		t_listrule:"Mô tả",	
		t_listpri:"Ưu tiên",
		t_listupbd:"Băng thông ngõ ra",
		t_listdownbd:"Băng thông vào",
		t_warning1:"Băng thông đầu vào luồng lên của bạn lớn hơn so với băng thông tối đa!",
		t_warning2:"Băng thông đầu vào luồng xuống của bạn lớn hơn so băng thông tối đa!",
		t_dslUp:"Tốc độ luồng dữ liệu lên hiện tại:",
		t_dslDown:"Tốc độ luồng dữ liệu xuống hiện tại:",
		t_hwNatEn:"Nếu Kiểm soát băng thông được kích hoạt, phần cứng NAT sẽ không thực hiện, vì hai mô-đun không thể làm việc cùng một lúc."
	},
	trafCtrlEdit:
	{
		et:"Điều khiển dải tần",
		t_iprange:"Dải IP:",
		t_portrange:"Khoảng cổng:",
		t_prio:"Ưu tiên:",
		t_prioNote:"(1 ý nghĩa ưu tiên cao nhất)",
		t_minrate:"Băng thông tối thiểu",
		t_maxrate:"Băng thông tối đa",
		t_up:"Băng thông ngõ ra:",
		t_down:"Băng thông vào:"
	},
	arpBind:
	{
		et:"Cài đặt liên kết",
		t_info:"Trang này hiển thị danh sách Binding ARP. Xin vui lòng bấm vào Thêm mới để tạo mục MAC Binding mới hoặc bấm chỉnh sửa để chỉnh sửa một mục hiện tại.",
		t_bind:"Liên kết ARP:",
		t_status:"Liên kết"
	},
	arpBindEdit:
	{
		et:"Cài đặt liên kết",
		t_info:"Trang này cho phép bạn thiết lập mục IP-MAC Binding.",
		t_bind:"Liên kết"
	},
	arpList:
	{
		et:"Danh sách ARP",
		importBtn: "Lựa chọn tải"
	},
	phDDNS:{
		et:"Cài đặt DDNS",
		t_url:"URL dịch vụ:",
		t_provider:"Nhà cung cấp dịch vụ:",
		t_reg1:"Vào đăng ký",
		t_reg2:"Vào đăng ký",
		t_reg3:"Vào đăng ký",
		t_reg4:"Vào đăng ký",
		t_domain1:"Tên miền:",
		t_domain2:"Tên miền:",
		t_domain3:"Tên miền 1:",
		t_domain4:"Tên miền 2:",
		t_domain5:"Tên miền 3:",
		t_domain6:"Tên miền 4:",
		t_domain7:"Tên miền 5:",
		t_en:"Kích hoạt DDNS",
		t_stat:"Tình trạng kết nối:",
		t_type:"Loại dịch vụ:",
		t_dnsinfo:"Thông tin tên miền:",
		login:"Đăng nhập",
		logout:"Đăng xuất"
	},
	diagnostic:{
		et:"Các công cụ chẩn đoán",
	    t_info:"Trạng thái kết nối Internet của thiết bị này có thể được kiểm tra trên trang này.",
		t_type:"Loại chẩn đoán",
		t_surfwan:"Kiểm tra kết nối giao diện WAN"
	},
    pingNTraceRoute:{
		et:"Các công cụ chẩn đoán",
		t_param: "Các thông số chẩn đoán",
		t_test_method: "Công cụ chẩn đoán:",
		t_ipping:"Ping",
		t_tracert:"Traceroute",
		t_addr:"Địa chỉ IP / Tên miền:",
		t_ping_pkt:"Đếm Ping:",
		t_ping_pkt_size:"Kích thước gói tin Ping:",
		t_ping_timeout:"Thời gian chờ Ping:",
		t_trace_hop:"Traceroute Max TTL:",
		t_result:"Các kết quả chẩn đoán",
		t_note2: "(0 - 65500 Bytes)",
		t_note3: "(1 - 60 giây)"
		
    },
	log:{
		et:"Bản ghi hệ thống",
		t_logtype:"Loại bản ghi:",
		t_loglevel:"Mức bản ghi:",
		t_time:"Thời gian",
		t_type:"Loại ",
		t_level:"Mức độ",
		t_content:"Nội dung",
		t_clear:"Xóa đăng nhập",
		t_save:"Lưu bản ghi",
		t_setting:"Cài đặt bản ghi"
	},
	logConf:{
		et:"Cài đặt syslog",
		t_local:"Lưu nội bộ",
		t_remote:"Lưu điều khiển từ xa",
		t_minlvl1:"Cấp độ thấp nhất",
		t_minlvl2:"Cấp độ thấp nhất",
		t_ip:"IP máy chủ",
		t_port:"Cổng máy chủ  ",
		t_fcname:"Tên chức năng nội bộ"
	},
	time:{
		et:"Cài đặt thời gian",
		t_time:"Cài đặt thời gian:",
		t_info:"Bấm vào lấy giờ GMT để cập nhật thời gian hệ thống từ Internet với các máy chủ được xác định trước hoặc bạn có thể thiết lập thời gian hệ thống bằng tay bằng cách nhập máy chủ NTP chỉ định (địa chỉ IP hoặc tên miền).",
		t_zone:"Múi giờ:",
		t_date:"Ngày:",
		t_year:"Năm",
		t_month:"Tháng",
		t_daytime:"Thời gian:",
		t_day:"Ngày ",
		t_hour:"giờ",
		t_minute:"Phút",
		t_second:"thứ cấp",
		t_npt1:"Máy chủ NTP 1:",
		t_npt2:"Máy chủ NTP 2:",
		GetTime:"Nhận giờ GMT",
		t_note:"(Chỉ khi kết nối internet hoạt động)",
		t_dst:"Tiết kiệm ánh sáng ban ngày:",
		t_dst_en:"Kích hoạt tính năng tiết kiệm ánh sáng:",
		t_dst_start:"Bắt đầu: ",
		t_dst_end:"Kết thúc:"
	},
	manageCtrl:{
		et:"Kiểm soát quản lý",
		t_stat:"Trạng thái người dùng hiện tại",
		t_type:"Loại người dùng:",
		t_ip:"Host IP Address:",
		t_mac:"Host MAC Address:",
		t_account:"Quản lý tài khoản",
		t_oldpwd:"Mật mã cũ:",
		t_newname:"Tên đăng nhập mới:",
		t_newpwd:"Mật mã mới:",
		t_service:"Cấu hình dịch vụ",
		t_http:"HTTP dịch vụ",
		t_avail:"Máy chủ có sẵn",
		t_local:"Quản lý nội bộ",
		t_remote:"Quản lý từ xa",
		t_tip:"Tên người dùng và mật mã không được vượt quá 15 ký tự!",
		t_ping_title:"ICMP(ping):",
		t_ping_remote:"Từ xa",
		t_ping_local:"Nội bộ"
	},
	cwmp:{
		et:"Thiết lập CWMP",
		t_info:"WAN Management Protocol (còn gọi là TR-069) cho phép tự động cấu hình máy chủ (ACS) để thực hiện cấu hình tự động, cung cấp, thu thập, và chẩn đoán để thiết bị này. Bạn có thể cấu hình chức năng này theo hướng dẫn của ISP của bạn",
		t_inform:"Thông báo:",
		t_interval:"Khoảng thời gian thông báo:",
		t_if:"Giao diện sử dụng bởi máy khách TR-069:",
		t_anywan:"Bất kỳ mạng WAN",
		t_display:"Hiển thị thông điệp SOAP trên bàn điều khiển nối tiếp:",
		t_auth:"Xác thực yêu cầu kết nối",
		t_cr_name:"Tên đăng nhập yêu cầu kết nối:",
		t_cr_pwd:"Mật mã yêu cầu kết nối:",
		t_cr_path:"Đường dẫn yêu cầu kết nối:",
		t_cr_port:"Cổng yêu cầu kết nối:",
		t_cr_url:"URL yêu cầu kết nối:",
		getRPCMethods:"Nhận phương pháp RPC"
	},
	snmp:{
		et:"Cài đặt SNMP",
		t_info:"Simple Network Management Protocol(SNMP) cho phép các ứng dụng quản lý nhận trạng thái cập nhật và thống kê từ SNMP trong thiết bị.",
		t_snmp:"SNMP Agent:",
		t_read:"Đọc chung:",
		t_set:"Cài đặt chung:",
		t_name:"Tên hệ thống:",
		t_desc:"Sự mô tả hệ thống:",
		t_locale:"Vị trí hệ thống:",
		t_concat:"Hệ thống liên lạc:",
		t_trapip:"IP quản lý trap:"
	},
	backNRestore:
	{
		et:"Sao lưu và khôi phục",
		t_info:"Bấm vào SAO LƯU để lưu tất cả các cấu hình hiện tại vào máy tính nội bộ của bạn như là tập tin rác. Rất khuyến nghị bạn sao lưu cấu hình hiện tại của bạn trước khi sửa đổi bất kỳ cài đặt hoặc nâng cấp phần mềm. ",
		t_backup:"Sao lưu",
		t_info2:"Bạn có thể khôi phục lại một tập tin cấu hình bin đã lưu trước đó.",
		t_file:"Tập tin cấu hình:",
		t_restore:"Khôi phục",
		t_notice:"Thông báo:",
		t_note1:"Các cấu hình hiện tại sẽ thay thế bằng tập tin cấu hình tải lên. Áp dụng sai quy trình có thể làm cho thiết bị bị không quản lý được .",
		t_note2:"Một khi quá trình khôi phục hoàn tất, thiết bị sẽ tự động khởi động lại. Vui lòng giữ nguồn cho thiết bị để tránh các sự cố có thể xảy ra cho thiết bị."
	},
	defaultCfg:{
		et:"Mặc định nhà sản xuất",
		t_info:"Nhấn vào đây để khôi phục lại tất cả các thiết lập bên trong thiết bị này lại để mặc định của nhà máy. Đó là khuyến cáo mạnh mẽ rằng bạn sao lưu cấu hình hiện tại của bạn trước khi bạn khôi phục lại mặc định nhà máy.",
		t_restore:"Khôi phục"
	},
	softup:{
		et:"Nâng cấp phần mềm",
		t_info:"Các tính năng mới sẽ khả dụng sau khi cập nhật firmware thành công.",
		t_file:"Đường dẫn tập tin phần mềm",
		t_swver:"Phiên bản phần mềm",
		t_hwver:"Phiên bản phần cứng",
		t_note1:"Vui lòng chọn phiên bản firmware chính xác phù hợp với phiên bản phần cứng của thiết bị.",
		t_note2:"Việc giữ nguồn cho thiết bị trong quá trình nâng cấp là rất quan trọng để tránh các hư hỏng có thể xảy ra với thiết bị.",
		t_note3:"After the upgrade process is complete, the device will reboot Tự độngmatically.",
		t_upgrade:"Nâng cấp"
	},
	restart:{
		et:"Khởi động lại hệ thống",
		t_info:"Bấm Reboot để khởi động lại thiết bị mà không áp dụng bất kỳ thay đổi nào các thiết lập hiện tại của bạn."
	},
	password: {
		et: "Mật mã",
		t_tip: "Tên người dùng và mật khẩu có thể chứa từ 1-15 ký tự và có thể không bao gồm khoảng trắng.",
		t_oldname: "Tên người dùng cũ",
		t_oldpwd: "Mật mã cũ",
		t_newname: "Tên đăng nhập mới",
		t_newpwd: "Mật mã mới",
		t_clear: "Xóa tất cả"
	},
	stat:
	{
		et:"Thống kê lưu lượng dữ liệu:",
		t_info:"Thống kê lưu lượng dữ liệu--LAN",
		t_stat:"Thống kê lưu lượng dữ liệu:",
		t_interval:"Khoảng thống kê:",
		t_list:"Danh sách thống kê:",
		t_total:"Tổng cộng",
		t_cur:"Hiện tại",
		tr_sta_op:"Hoạt động",
		tr_sta_addr:"Địa chỉ IP<br/>Địa chỉ MAC",
		tr_sta_pkts1:"Gói tin ",
		tr_sta_bytes1:"Bytes",
		tr_sta_pkts2:"Gói tin ",
		tr_sta_bytes2:"Bytes"
	},
	iptv:
	{
		t_title_itv:"Cài đặt IPTV",
		t_title_qs:"Cài đặt nhanh - IPTV",
		t_dsl_tip:"Bạn có thể cài đặt tham số IPTV tại trang này. Nếu bạn muốn cài đặt cổng WLAN cho kết nối IPTV, vui lòng kích hoạt vô tuyến không dây.",
		t_ethl_tip:"Bạn có thể cài đặt tham số IPTV tại trang này. Nếu bạn muốn cài đặt cổng WLAN cho kết nối IPTV, vui lòng kích hoạt vô tuyến không dây.",
		t_iptv_tip_enable:"Kích hoạt IPTV",
		t_full_warn:"Cảnh báo: Nếu bảng nhập kết nối mạng WAN đã đầy, vui lòng vào mạng-> WAN để xóa một mục.",
		t_iptv_tip1:"Vui lòng chọn cổng LAN chỉ định cho kết nối IPTV và kết nối set-top-box(STB) đến cổng đã được chỉ định.",
		t_iptv_tip2:"Lưu ý: Khi cổng WLAN được cài đặt cho kết nối IPTV, tính năng không dây sẽ chỉ khả dụng cho kết nối IPTV đó mà thôi.",
		t_iptv_tip3:"Vui lòng cài đặt tham số PVC cho kết nối IPTV.",
		t_iptv_isp:"ISP:",
		t_iptv_vpi:"VPI",
		t_iptv_vci:"VCI",
		t_iptv_vlanTag:"Thẻ Vlan",
		t_iptv_vlanValue:"Giá trị Thẻ:"
	},
	ethIptv:
	{
		t_et:"Cài đặt IPTV",
		t_igmp_version:"Phiên bản IGMP",
		t_iptv_mode:"Mẫu",
		t_iptv_enable:"Kích hoạt IPTV"
	},
	autoReboot:
	{
		et:"Tự động khởi động lại",
		t_autoReboot:"Tự động khởi động lại",
		t_auto_day:"Ngày:",
		t_auto_time:"Thời gian:"
	},
	voice_account:
	{
		t_maxconf:"Tối đa 8 mục có thể được cấu hình.",
		t_inner1:"xuống",
		t_inner2:"up"
	},
	voice_addaccount:
	{
		t_st:"Cài đặt Tài khoản SIP cơ bản",
		t_displayname:"Tên hiển thị",
		t_stsip:"Cài đặt Tài khoản SIP nâng cao",
		t_preftime:"Ptime nhận ưu tiên",
		t_priority:"Ưu tiên",
		t_high:"1--high",
		t_low:"8--low",
		t_incomingcall:"Định tuyến cuộc gọi đến",
		t_mwi:"MWI",
		t_prefcode:"Bộ giải mã ưu tiên",
		t_prefcode1:"Bộ giải mã ưu tiên 1",
		t_prefcode2:"Bộ giải mã ưu tiên 2",
		t_prefcode3:"Bộ giải mã ưu tiên 3",
		t_prefcode4:"Bộ giải mã ưu tiên 4",
		t_option1:"nghỉ",
		t_option2:"PSTN 2nd stage dial"
	},
	voice_addblacklist:
	{
		t_blacklist:"Số danh sách đen"
	},
	voice_adddialplan:
	{
		t_maxlen:"Độ dài tối đa",
		t_dialendwith:"Dial End With",
		t_timeout:"Thời gian nghỉ  ",
		t_endtimeout:"#/hết giờ",
		t_strip:"Prefix dải",
		t_replace:"Tiền tố thay thế",
		t_addnum:"Thêm số",
		t_operatSubText:"chiều dài dải",
		t_inter:"Giao diện kích hoạt",
		t_example:"Ví dụ: 3 thiết lập điển hình",
		t_dialnum:"Quay số",
		t_dialoutnum:"Gọi điện số",
		t_strippref:"Prefix dải: chiều dài dải 3",
		t_replacepref:"Tiền tố thay thế: thay thế bằng 1865555",
		t_sipaccount1:"Tài khoản SIP 1",
		t_addnum1:"Thêm số: thêm số 17951",
		t_sipaccount2:"Tài khoản SIP 2",
		t_name:"Số thay thế",
		t_inner1:"Thay thế bằng"
	},
	voice_addforbiddencall:
	{
		t_interbarring:"Giao diện chặn cuộc gọi"
	},
	voice_addspeeddial:
	{
		t_info:"Nhập số điện thoại trong ô số cùng với số quay nhanh trong ô quay số sanh. Sau khi hoàn tất, chỉ cần quay 1 đi theo sau bằng #, để quay số điện thoại được chỉ định.",
		t_name:"Quay số tốc độ"
	},
	voice_addwhitelist:
	{
		t_whitelist:"Số danh sách trắng"
	},
	voice_advance:
	{
		t_advan:"Cài đặt nâng cao ",
		t_sipadvan:"Cài đặt SIP Nâng cao",
		t_bound:"Tên giao diện giới hạn:",
		t_dscpsip:"DSCP cho SIP:",
		t_dscprtp:"DSCP cho RTP:",
		t_dtmf:"Cấu hình đặt lại DTMF:",
		t_sipinfo:"Thông tin SIP",
		t_inband:"Trong băng thông",
		t_registimeout:"Thời gian chờ hết hạn đăng ký:",
		t_regisinterval:"Khoảng thời gian thử đăng ký lại:",
		t_sipprotocol:"Giao thức chuyển SIP",
		t_t38support:"Kích hoạt tính năng T 38 hỗ trợ.",
		t_siptag:"Kích hoạt thẻ SIP  phù hợp (bỏ chọn Vonage Interop).",
		t_pstnsetup:"Cài đặt PSTN",
		t_incomingfrom:"Định tuyến cuộc gọi PSTN đến:",
		t_sipurl:"SIP URI của thiết bị đầu cuối PSTN",
		t_advaninfo:"Hỗ trợ đảo cực PSTN. (Vui lòng giữ giá trị mặc định không chọn hộp chọn, trừ khi VSP của bạn yêu cầu bạn kích hoạt)",
		t_name1:"Thời gian chờ hết hạn đăng ký ",
		t_name2:"Khoảng thời gian thử đăng ký lại",
		t_name3:"Đường truyền",
		t_option1:"Điện thoại nghỉ",
		t_option2:"Điện thoại - Điện thoại vật lý",
		t_option3:"VOIP",
		t_option4:"VoIP - VoIP call"
	},
	voice_blacklist:
	{
		t_title1:"Chọn Thêm hoặc Xoá để cấu hình trong danh sách đen.",
		t_name:"Danh sách đen."
	},
	voice_calllog:
	{
		t_title:"Bảng dưới đây hiển thị 100 bản ghi cuộc gọi cuối cùng. Bấm vào \"Cấu hình\" để chọn kiểu bản ghi sẽ được hiển thị trong Xem bản ghi cuộc gọi.",
		t_no:"Không",
		t_name1:"VoIP",
		t_name2:"đến",
		t_name3:"from ",
		t_name4:"Đã kết nối",
		t_name5:"Không có kết nối",
		t_name6:"Hội nghị",
		t_name7:"chuyển nội bộ",
		t_name8:"chuyển từ xa",
		t_name9:"chuyển từ xa",
		t_name10:"chuyển tiếp nội bộ",
		t_name11:"IP",
		t_name12:"Từ chối"
	},
	voice_configcalllog:
	{
		t_title:"Trang này cho phép bạn chọn kiểu bản ghi sẽ được hiển thị trong xem bản ghi cuộc gọi.",
		t_calltype:"Loại cuộc gọi:",
		t_incomingvoip:"Cuộc gọi đến (VoIP)",
		t_outgoingvoip:"Outgoing(VoIP)",
		t_incomingpstn:"Cuộc gọi đến (PSTN)",
		t_outpstn:"Outgoing(PSTN)",
		t_protype:"Loại quá trình",
		t_localforward:"Chuyển tiếp nội bộ",
		t_remoteforward:"Chuyển từ xa",
		t_localtransfer:"Chuyển nội bộ",
		t_remotetransfer:"Chuyển từ xa",
		t_conference:"Hội nghị",
		t_unconnected:"Không có kết nối"
	},
	voice_configusbmail:
	{
		t_note:"Lưu ý: Vui lòng làm mới trang khi xảy ra tình trạng USB được cắm nóng!",
		t_notEnough:"Không có đủ dung lượng hộp thư điện tử USB có sẵn!",
		t_enopernotify:"Kích hoạt tính năng thông báo Local Play",
		t_enwavFormat:"Kích hoạt định dạng Global.Wav",
		t_enremoveVoice:"Kích hoạt tính năng loại bỏ hết hạn thoại",
		t_expire:"Ngày hết hạn (7 ~ 15):",
		t_duration:"Giới hạn thời gian thoại (20 ~ 120s):",
		t_usbCapText:"Dung lượng hộp thư điện tử USB(0~0M):",
		t_enphone:"Điện thoại đã bật",
		t_mode:"Chế độ điện thoại",
		t_noanswer:"không trả lời",
		t_busy:"Chuyển tiếp khi \"bận\"",
		t_noanswer:"Chuyển tiếp khi \"không trả lời\"",
		t_busyandnoanswer:"Chuyển tiếp khi \"bận\" và \"không trả lời\"",
		t_customNotify:"Tùy chỉnh ghi âm thông báo bằng giọng nói",
		t_notify:"Thông báo ghi âm bằng giọng nói:",
		t_def:"mặc định",
		t_custom:"tùy chỉnh",
		t_rPIN:"Truy cập PIN từ xa",
		t_name1:"Ngày hết hạn",
		t_name2:"Giới hạn thời gian thoại",
		t_name3:"Dung lượng hộp thư điện tử USB",
		t_name4:"Truy cập PIN của điện thoại từ xa",
		t_name5:"Dung lượng hộp thư điện tử USB"
	},
	voice_dialplan:
	{
		t_info:"Tối đa 50 mục có thể được cấu hình.",
		t_op:"Op",
		t_name1:"dải",
		t_name2:"Số ký tự",
		t_name3:"Giữ",
		t_name4:"Thay thế",
		t_name5:"Với",
		t_name6:"Thêm vào",
		t_name7:"Trước",
		t_name8:"Đường truyền 2/",
		t_name9:"Đường truyền 1/"
	},
	voice_emergencycall:
	{
		t_info:"Vui lòng lưu ý một số số điện thoại khẩn cấp (ví dụ 911) chỉ có thể được gọi thông qua đường dây PSTN và không thể thực hiện qua đường dây VoIP.",
		t_emphonenum:"Số điện thoại khẩn cấp",
		t_name:"Cuộc gọi khẩn cấp"
	},
	voice_firewall:
	{
		t_encallfirewall:"Kích hoạt tường lửa cuộc gọi:",
		t_mode:"Chế độ tường lửa cuộc gọi",
		t_black:"Đen",
		t_white:"Trắng",
		t_rejectall:"Từ chối tất cả",
		t_st:"Chú ý!",
		t_blackinfo:"Trong chế độ danh sách den, tất cả cuộc gọi trong danh sách đen sẽ bị từ chối.",
		t_whiteinfo:"Ở Chế độ Danh sách trắng, chỉ có cuộc gọi từ số được nhập trong Danh sách trắng được cho phép.",
		t_rejectinfo:"Tại Chế độ Từ chối tất cả, tất cả cuộc gọi sẽ bị từ chối."
	},
	voice_forbiddencall:
	{
		t_info:"Tối đa 20 mục có thể được cấu hình.",
		t_forbidden:"Chặn"
	},
	voice_line:
	{
		t_et:"Cài đặt điện thoại",
		t_enphone:"Điện thoại bật",
		t_st1:"Thiết lập quay số",
		t_pri:"Ưu tiên Dial Plan",
		t_fallback:"Dự phòng đến PSTN",
		t_anoncall:"Cuộc gọi nặc danh:",
		t_res:"Quay số hạn chế:",
		t_aforbcall:"Theo cấm gọi",
		t_enwarmline:"Kích hoạt WarmLine:",
		t_warmtime:"Thời gian WarmLine:",
		t_warmnum:"Số WarmLine:",
		t_head3:"SIP/PSTN",
		t_num1:"Số 1",
		t_num2:"Số 2",
		t_num3:"Số 3",
		t_num4:"Số 4",
		t_num5:"Số 5",
		t_st2:"Cài đặt trả lời",
		t_mwimode:"Chế độ MWI:",
		t_vmwi:"VMWI",
		t_clid:"CLID",
		t_anonycall:"Chặn cuộc gọi nặc danh:",
		t_dnd:"DND(Không làm phiền):",
		t_callwait:"Chờ cuộc gọi:",
		t_onbusy:"Chuyển tiếp khi  &quot;busy&quot;:",
		t_forwonanswer:"Chuyển tiếp khi  &quot;không trả lời&quot;:",
		t_usbtrigon:"Vui lòng lưu ý mở cài đặt cảnh báo hộp thư thoại USB trước đó của bạn.",
		t_noun:"không trả lời/không điều kiện",
		t_usbtrig:"Vui lòng lưu ý cài đặt cảnh báo hộp thư thoại USB trước đó của bạn.",
		t_busynoun:"bận / không trả lời / vô điều kiện",
		t_notime:"&quot;Không trả lời&quot; thời gian:",
		t_sec:"Giây (5~60)",
		t_st3:"Cài đặt điện thoại",
		t_vad:"Hỗ trợ VAD:",
		t_speaker:"Tăng loa:",
		t_mic:"Độ lợi Mic:",
		t_name:"\"không trả lời\" thời gian"
	},
	voice_speeddial:
	{
		t_info:"Tối đa 30 mục có thể được cấu hình."
	},
	voice_usbmail:
	{
		t_note:"Lưu ý: Sau khi bấm chọn &quot;Phát&quot, vui lòng đợi trong giây lát.",
		t_item:"Mục trên trang",
		t_phone:"Điện thoại  ",
		t_start:"Thời gian bắt đầu",
		t_length:"Chiều dài",
		t_audition:"Nghe thử",
		t_readflag:"Cờ đọc",
		t_select:"Đã chọn",
		t_inner1:"Mục lục",
		t_inner2:"Chạy  ",
		t_inner3:"Không",
		t_inner4:"Cuối",
		t_inner5:"Tiếp theo",
		t_inner6:"Cuối"
	},
	voice_whitelist:
	{
		t_info:"Chọn Thêm hoặc Xoá để cấu hình trong danh sách trắng.",
		t_name:"Danh sách trắng"
	},
	voice_featurecode:
	{
		t_note:"Lưu ý: Số điện thoại bắt đầu với bất cứ mã tính năng nào sau đây sẽ không thể thực hiện cuộc gọi.",
		t_discallwaittag:"Vô hiệu hóa cuộc gọi chờ:",
		t_encallwaittag:"Kích hoạt tính năng cuộc gọi chờ cho cuộc gọi hiện tại:",
		t_discallwaitcurtag:"Vô hiệu hóa cuộc gọi chờ cho các cuộc gọi hiện tại:",
		t_encallwaitcurtag:"Kích hoạt tính năng cuộc gọi chờ cho cuộc gọi hiện tại:",
		t_encallbacktag:"Kích hoạt tính năng gọi lại cho cuộc gọi hiện tại:",
		t_scallfortag:"Cài đặt chuỗi quay số chuyển tiếp cuộc gọi:",
		t_disallcallfortag:"vô hiệu hóa chuyển hướng tất cả các cuộc gọi",
		t_fcallnoanswertag:"Chuyển tiếp cuộc gọi khi không trả lời:",
		t_fcallonbusytag:"Chuyển tiếp cuộc gọi nếu bận:",
		t_forwardallcalltag:"Chuyển tiếp tất cả cuộc gọi:",
		t_callreturnintag:"Cuộc gọi gần đây [cuộc gọi đến]",
		t_callreturnouttag:"Cuộc gọi gần đây [cuộc gọi đi]",
		t_actwarmlinetag:"Kích hoạt dòng ấm:",
		t_deactwarmlinetag:"Tắt warm line:",
		t_actanonycalltag:"Kích hoạt cuộc gọi nặc danh:",
		t_deactanonycalltag:"Tắt những cuộc gọi nặc danh:",
		t_enanonycurtag:"Kích hoạt tính năng cuộc gọi nặc danh cho các cuộc gọi hiện tại:",
		t_disanonycurtag:"Vô hiệu hóa các cuộc gọi nặc danh cho các cuộc gọi hiện tại:",
		t_enanonytag:"Kích hoạt tính năng cuộc gọi nặc danh",
		t_disanonytag:"Vô hiệu hóa các cuộc gọi nặc danh:",
		t_actdonotdisturbtag:"Kíck hoạt làm-không-phiền:",
		t_deactdonotdisturbtag:"Tắt không-làm-phiền:",
		t_barringtag:"Chặn cuộc gọi:",
		t_outcallpritag:"Cài đặt cuộc gọi đi ưu tiên:",
		t_voicemsgtag:"Nghe tin nhắn thoại:",
		t_storevoicemsgtag:"Tin nhắn thoại lưu trữ bên trong thiết bị lưu trữ USB:",
		t_intercalltag:"Cuộc gọi nội bộ:",
		t_actnetpritag:"Kích hoạt bảo mật mạng:",
		t_deactnetpritag:"Tắt bảo mật mạng:",
		t_name1:"Và",
		t_name2:"Không thể giống nhau"
	}
};

var if_str =
{
	NULL:"",
	LAN:"LAN & WLAN",
	Internet:"Kết nối Internet",
	Public:"Kết nối thứ cấp"
};

